### ISSUE TITLE
Discussion: defaulting to wrap the main panel's contents

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazydocker#100]
Should we make the main panel wrap by default? I personally think so, as do some people I've talked to. 
There are two reasons why initially the default was set to not wrap:
1) `less` doesn't wrap and that's a program most people are familiar with
2) (the main reason) if I want to render all logs via `docker-compose logs` across all my services, and I modify the command template not to have `--tail=300`, AND I'm wrapping in my main panel, lazydocker goes to 100% CPU. Without wrapping it sits at 20%.

Using instruments I found out what was causing this CPU spike:

![image](https://user-images.githubusercontent.com/8456633/60721489-7421be00-9f71-11e9-86cd-abd1a48ce77f.png)

Basically our LineWrap function is being called a lot, and it spends a lot of time in the inTables function in runewidth, which is a library for working out the width of a given rune (considering that runes can be emojis, mandarin characters etc).

Even if I hardcode runewidth to always return 1, we still see quite a bit of CPU usage. I think that the proper solution here is to find a way to not process so many runes when only a tiny slice of them actually end up being rendered inside the panel. But I'm not sure what that solution entails.

Until we work that out, I think the default for wrapping the main panel should remain false, but I personally would like to eventually set the default to true.

As a final note, we actually don't currently support defaults of true, because we use `omitempty` on the config's yaml fields, meaning if you set the value to 'false' in your config to override the default, it will be treated like a zero value and ignored when merging in the user config into the default config. I spent a little time trying to use indirection (i.e. using a boolean pointer so that the zero value becomes `nil`) but didn't work it out.

**Comment by arun0009** [comment]
Can we make it scrollable if wrapping takes too much of CPU?

**Comment by jesseduffield** [comment]
@arun0009 yep currently you can horizontally scroll if wrapping is disabled

**Comment by jesseduffield** [comment]
as of https://github.com/jesseduffield/lazydocker/pull/339 we're now defaulting to wrapping the main panel
