### ISSUE TITLE
Container CPU usage above 100%

### ISSUE THREAD

**Issue by dawidd6** [jesseduffield/lazydocker#104]
**Describe the bug**
The image tells more than thousand words :)

**To Reproduce**
For example run `go get github.com/docker/cli/cmd/docker` in container and observe.

**Expected behaviour**
CPU usage percents not exceeding 100.

**Screenshots**
![Screenshot from 2019-07-05 21-17-26](https://user-images.githubusercontent.com/9713907/60741925-9ca6b980-9f6b-11e9-8db7-2d800bb07820.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - master
 - c04867b36de6d05dfb5b41ba0fbe4c3bbc1f89c4

**Additional context**
Seems like it is an issue with Docker itself, cause `docker stats` is producing such output.

---

Maybe divide this percentage by number of CPU cores the machine has? I have 4, so 340% is high.

**Comment by jesseduffield** [comment]
I actually think we're better off displaying exactly what docker stats would display. I've got 8 cores, so I'm accustomed to occasionally seeing CPU usages go beyond 100%, as are others at my workplace.

**Comment by SvenDowideit** [comment]
340% should tell you that your container is using 4 (or more) cores. it might be helpful to explain that in the UI though.

**Comment by jesseduffield** [comment]
I can't think of any clear way of expressing the multi-core nature of the percentage in the UI, so I'm going to close this ticket. But if somebody does want that as a feature, feel free to raise a feature request.
