### ISSUE TITLE
Panic: docker socket permission denied

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazydocker#12]
Me and i guess a lot of others will have no permissions to access the docker socket by default, (see error)  
When i type lazydocker it panics because docker can't access the docker socket.  

The error:
```
mark@that-laptop-with-solus-os ~> lazydocker
2019/06/30 11:56:06 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*errors.withStack Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.25/images/json: dial unix /var/run/docker.sock: connect: permission denied
/home/mark/go/src/github.com/jesseduffield/lazydocker/main.go:63 (0x81fed1)
	main: newErr := errors.Wrap(err, 0)
/usr/lib64/golang/src/runtime/proc.go:200 (0x42f1dc)
	main: fn()
/usr/lib64/golang/src/runtime/asm_amd64.s:1337 (0x45a131)
	goexit: BYTE	$0x90	// NOP
```

It would be nice if lazydocker just exits normally with a nice error like:  
```
ERROR: Can't access docker socket at: unix:///var/run/docker.sock
Run lazydocker as root or read https://docs.docker.com/install/linux/linux-postinstall/
```

**Comment by jesseduffield** [comment]
Hey @mjarkk long time no see :)

That sounds reasonable. I'm thinking that in main.go we could catch the error, check if it contains something like `Got permission denied while trying to connect to the Docker daemon socket` and then print the error you came up with?

**Comment by jesseduffield** [comment]
I've put up a PR here https://github.com/jesseduffield/lazydocker/pull/14 let me know what you think :)

**Comment by jesseduffield** [comment]
closin :)
