### ISSUE TITLE
macOS - XDG base directory specification

### ISSUE THREAD

**Issue by michaelrigart** [jesseduffield/lazydocker#125]
Hi,

I know the application uses github.com/shibukawa/configdir library to define the config dir location on different platforms. I don't know if this is something that is being forced by the library, or is configurable.

Even though I'm a macOS user, I still use the XDG base directory specification for all tools where possible.

Is it possible for lazydocker to check whether the environment varialbe XDG_CONFIG_HOME is present, before forcing the config directory to be in ~/Library/Application Support ?

Even though users might use macOS, they are still free to apply XDG.

**Comment by dawidd6** [comment]
It is forced by the library.

We can either fork the library, make a pull request to upstream or just create a workaround here:
https://github.com/jesseduffield/lazydocker/blob/690a7c62f439fbe3096c7a8595028511724eaab9/pkg/config/app_config.go#L414-L423

@jesseduffield @mjarkk what do you think fellas?

**Comment by jesseduffield** [comment]
that package looks perfect :)

**Comment by dawidd6** [comment]
Will do today.
