### ISSUE TITLE
No Services shown

### ISSUE THREAD

**Issue by humpalum** [jesseduffield/lazydocker#134]
**Describe the bug**
After setting everything up, there are no Services shown on the left side. 
![image](https://user-images.githubusercontent.com/11175099/61526917-a45e6780-aa1b-11e9-9ad5-da25b73b276f.png)

**To Reproduce**
1. I simply installed it with the binary release script and started it with "lazydocker"

**Expected behaviour**
Services and Container should be visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian
 - Lazydocker Version 
Version: commit=cca69e64f3225d44d1ffd115673d0ce26d153191, build date=2019-07-07T12:52:10Z, build source=binaryRelease, version=0.5.5, os=linux, arch=amd64

**Additional context**
I checked the Logfiles when running with -debug and the following warning is logged quite often:
`{"buildDate":"2019-07-07T12:52:10Z","commit":"cca69e64f3225d44d1ffd115673d0ce26d153191","debug":true,"level":"warning","msg":"'docker-compose config --hash=*': 1.503660111s","time":"2019-07-19T11:54:42+02:00","version":"0.5.5"}`

so i tried to run this command manually in my shell resulting in the following: 
```$docker-compose config --hash=*
Validate and view the compose file.

Usage: config [options]

Options:
    -q, --quiet     Only validate the configuration, don't print
                    anything.
    --services      Print the service names, one per line.
```

So my guess is, that my docker-compose is somehow not  good for lazydocker, however version requirements should be met: 
```$docker-compose --version
docker-compose version 1.8.0, build unknown
```
Same with docker version: 
```
$docker version
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056dbc
 Built:             Thu Apr 11 04:44:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

Thank you for helping me out :)

**Comment by dawidd6** [comment]
Please read the [requirements](https://github.com/jesseduffield/lazydocker#requirements).

**Comment by humpalum** [comment]
Im sorry, mistook the version numbers.
