### ISSUE TITLE
Moving formula to homebrew-core

### ISSUE THREAD

**Issue by chenrui333** [jesseduffield/lazydocker#135]
I wonder if we want to move the formula to `homebrew-core` like `lazygit`.

Related effort: https://github.com/Homebrew/homebrew-core/pull/42239

**Comment by dawidd6** [comment]
Well, there are some pros and cons with this move.

Pros:
- no need to tap, just install
- can install HEAD

Cons:
- slightly slower updates
- need to submit PRs manually with every release
- goreleaser is already configured to automatically push to tap on new release and it works well

Sooo, I don't know about this.
@jesseduffield ?

**Comment by jesseduffield** [comment]
Yeah this is a tough one. People really value to the ability to `brew install` without worry about taps, but I've been pretty bad at keeping homebrew-core up to date with lazygit.

At any rate I think we should keep this issue open and maybe once we feel like we've got all the major current bugs fixed we can revisit this and look into getting lazydocker into homebrew-core.

**Comment by mjarkk** [comment]
How about we (jesse, me, dawidd6) only make a pr for major and minor releases like: `0.1, 0.2, 0.3, 1.0, etc` and if the community wants a patch they can submit a pr.  

But i don't have experience with home brew neither there git repo's so this might be a dumb idea :)

**Comment by jesseduffield** [comment]
This is fixed now
