### ISSUE TITLE
add zplug installation section to Readme

### ISSUE THREAD

**Issue by gaerfield** [jesseduffield/lazydocker#137]
Please consider adding an Installation-Section for zplug-users, so they could use your tool as plugin.

[zplug](https://github.com/zplug/zplug)-users could use the [plugin-syntax](https://github.com/zplug/zplug#example) the install lazydocker:
```
zplug "jesseduffield/lazydocker", \
    from:gh-r, \
    use:"*Linux*x86*64*", \
    as:command
```
Set your architecture in accordance to the packages on the [release-page](https://github.com/jesseduffield/lazydocker/releases) with the "use"-tag, ie:
* mac-users should put `use:"*Darwin*64*"`
* arm-users could put `use:"*Linux*arm*64*"`

**Comment by mjarkk** [comment]
Seems fine to me tough there is 1 problem, the readme is getting way to full with how to install scripts to the point where it looks messy.  

I think it's better we put this under a expend line as dune with the `Click if you have an ARM device`, or make a repo wiki page just for how *to install in other package managers*.

**Comment by dawidd6** [comment]
@gaerfield do you know any other projects that have `zplug` installation instructions in their READMEs besides zsh related ones?

**Comment by gaerfield** [comment]
Besides zsh-projects: no
Even with zsh-projects its rare and more common within an "installation"-wiki-page than in within the README (I rechecked my installed plugins, only [powerlevel9k](https://github.com/Powerlevel9k/powerlevel9k/wiki/Install-Instructions#option-5-install-for-zplug) and [fzf-fasd ](https://github.com/wookayin/fzf-fasd) have some documentation).

**Comment by mjarkk** [comment]
In that case i think it's better to not put this in the README.  

Maybe it's better for zplug to have there own install wiki for packages, or have a website where users can search for zplug packages.

**Comment by gaerfield** [comment]
I'm fine with closing this issue. The decision, not to put the info in the README, seems reasonable to me.

I remember, there was some time in the past a wiki-page for such zplug-configs. I don't know the reason, why it got removed (probably it was too messy). In my opinion zplug itself isn't a good place either, there are too many packages. A typical integration-problem: one side has a very flexible package-system, the other side could be integrated in many different systems. And both sides would be overwhelmed in documenting all variations. We still have this issue, that's some documentation 😊

Do you close this issue? (Or should I do it? I'm not sure about the process.)

**Comment by mjarkk** [comment]
I'll close this issue because there isn't more to say for now.  
Still tanks for making it!
