### ISSUE TITLE
High memory use, leak?

### ISSUE THREAD

**Issue by matthew-d-jones** [jesseduffield/lazydocker#139]
Left lazydocker running for ~3 days, memory use increased to 14 GB. There were no running containers for most of this time.

**To Reproduce**
Leave lazydocker running?

**Expected behaviour**
Memory use to remain low.

**Desktop (please complete the following information):**
```
lazydocker --version
Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=linux, arch=amd64
```
Ubuntu 18.04

**Comment by mjarkk** [comment]
This is fixed since v0.5.5 and you are running v0.3  
Can you try to update lazydocker and see if that fixed the problem?
