### ISSUE TITLE
add image name to container frame

### ISSUE THREAD

**Issue by anjiawei1991** [jesseduffield/lazydocker#144]
![2019-08-02 10-15-14屏幕截图](https://user-images.githubusercontent.com/48538419/62339904-3ed8a380-b510-11e9-99b3-271ea6ce21cf.png)

I think the image name should be added to the container frame because it's a really important thing especially when I haven't named the container such as the `nice_cartwright` and `angry_chatterjee` in the above picture. And, I can't see the image name in any of the right pages.

**Comment by anjiawei1991** [comment]
![2019-08-02 10-57-23屏幕截图](https://user-images.githubusercontent.com/48538419/62341058-62055200-b514-11e9-9958-e5c5c5eaa5ec.png)

I have done that job, and it looks nice I think.

**Comment by mjarkk** [comment]
Have you also tried looking at it in a small terminal window?  
I think the 0.00% is going to out of the window, and the cpu usage is for me more important than the image names.  

The problem with these wide lines is that not everyone has there terminal maximized and for those these these changes look wrong.  
For example when i start lazydocker these changes will look like this:  
```
|running nice_cartwright  fortu|
|created angry_chatterjee f14d3|
|running nsq_nsqd_1       nsqio| <- this container name is now completly useless because i only see the username of who made the container

-> compaired to this
|running nice_cartwright  0.14%|
|created angry_chatterjee 0.00%|
|running nsq_nsqd_1       5.50%|
```

**Comment by anjiawei1991** [comment]
![2019-08-02 15-05-55屏幕截图](https://user-images.githubusercontent.com/48538419/62351056-1617d480-b537-11e9-9430-5bef4afc2a3a.png)


@mjarkk It works well if window's width is greater than 1150. CPU is indeed important. So another way is to place the image name behind the CPU. Or more sophisticated, decide wether to show the image name depend on the  window's size, but it will bring complexity. 

But I do think the image name is very important. I always use the terminal in max window size mode, and I think most of users do this.

**Comment by jesseduffield** [comment]
I've got no issue with showing the image name after the cpu.

Although, it seems that there is a strong use case for being able to see a lot of things related to a panel list item in the side panel. Perhaps we should consider having a toggle-able expanded side panel view for when you want to see extra information about all your e.g. containers at once.

At any rate for this issue I'm happy for the image name to go after the cpu.

**Comment by anjiawei1991** [comment]
@jesseduffield 
It sounds good to have a toggle-able expanded side panel view and that could be another issue.

I think I can change my codes and fix this one: show the image name after the CPU.
