### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by brianlechthaler** [jesseduffield/lazydocker#146]
**Describe the bug**
After building the docker image for this repo, then running the image in a new container an error was thrown.

**Command Line Output**
`2019/08/04 03:56:50 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*os.PathError open /dev/tty: no such device or address
/tmp/gobuild/main.go:88 (0x8a0f69)
/usr/local/go/src/runtime/proc.go:200 (0x42d79c)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x4585b1)
`

**To Reproduce**
1. `cd lazydocker`
2. `docker build -t lazydocker .`
3. `docker run lazydocker:latest`

**Additional Info**
- **uname -a output**: `Linux ip-172-31-5-246 4.15.0-1044-aws #46-Ubuntu SMP Thu Jul 4 13:38:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- **commit hash**      : `8970352efc4a046c01de6263b1a9ecd271ef29fc`

**Comment by dawidd6** [comment]
Please read the README.

Run it like this:
```sh
docker run -it -v \
/var/run/docker.sock:/var/run/docker.sock \
lazydocker
```
