### ISSUE TITLE
Latest version doesnt respect DOCKER_HOST anymore

### ISSUE THREAD

**Issue by freemo** [jesseduffield/lazydocker#154]
Upgraded to the latest release of lazydocker and it no longer honors remote hosts by setting the DOCKER_HOST env variable. It always just ignores it and connects locally now. Old versions used to work.

**Comment by dawidd6** [comment]
I think I know what is wrong, will try to fix it quickly and make new patch release.

**Comment by freemo** [comment]
@dawidd6 much appreciated. I install through brew usually so once its availible ill have to figure out how to install and test.

**Comment by dawidd6** [comment]
@freemo you should be able now to `brew update` lazydocker now, if you use the tap.

Please try and report back if it's fixed.

**Comment by freemo** [comment]
Ill move over to the tap, thanks.

**Comment by freemo** [comment]
@dawidd6 im not entirely sure if the tap pulled in your fix as you suggested but the problem is still occuring to me.

**Comment by dawidd6** [comment]
What is the output of `lazydocker --version`?

**Comment by freemo** [comment]
@dawidd6 nvm the problem is your tap instuctions didnt work, at least for me. I did this and it didnt work:

```
brew uninstall lazydocker
brew tap jesseduffield/lazydocker
brew install lazydocker
```

All that did was install the standard version not the tap version (because they had the same name). When i did the following however it did work:

```
brew uninstall lazydocker
brew tap jesseduffield/lazydocker
brew install jesseduffield/lazydocker/lazydocker
```

You may wish to update your documentation.

**Comment by dawidd6** [comment]
Oh dang, didn't know that. Sure will do, thanks.
