### ISSUE TITLE
Return from main panel after help menu

### ISSUE THREAD

**Issue by jakobkogler** [jesseduffield/lazydocker#158]
**Describe the bug**
After entering the main panel, and opening the help menu, it is no longer possible to exit the main panel with key bindings.

**To Reproduce**

1. Start `lazydocker`
2. Enter the main panel of the first container with `<ENTER>`
3. Open help menu with `x` or `?`
4. Close the help menu with `<ESC>`
5. Try to leave the main panel with `<ESC>`

The last command doesn't work, and the main panel stays focused. It also shows some other funky behaviors, like changing tabs doesn't work very well.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10
 - Lazydocker VersionVersion:

```
    Version: 0.7.1
    Date: 2019-08-25T17:27:17Z
    BuildSource: binaryRelease
    Commit: febfce995c852ca9d1977febc6098165f7e31c8f
    OS: linux
    Arch: 386
```

**Comment by dawidd6** [comment]
@jakobkogler I think this could be fixed in this [PR](https://github.com/jesseduffield/lazydocker/pull/159).

Can you build it from source and do some testing?

**Comment by jakobkogler** [comment]
Hmm, somehow I can't get the app to build/run correctly.
I did:

```
docker build -t lazyteam/lazydocker \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    --build-arg DOCKER_VERSION="v$(docker -v | cut -d" " -f3 | rev | cut -c 2- | rev)"\
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg VERSION=`git describe --abbrev=0 --tag` \
    .
```

Both with and without the `DOCKER_VERSION` argument, and then tried to start it with 

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock <image>
```

I get the error message:

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).layout(0xc00036a420, 0xc00030e420, 0xc000304018, 0xc0005e9768)
        /tmp/gobuild/pkg/gui/layout.go:97 +0x1d05
github.com/jesseduffield/gocui.ManagerFunc.Layout(0xc0002cef70, 0xc00030e420, 0x0, 0x1)
        /tmp/gobuild/vendor/github.com/jesseduffield/gocui/gui.go:390 +0x30
github.com/jesseduffield/gocui.(*Gui).flush(0xc00030e420, 0x0, 0x0)
        /tmp/gobuild/vendor/github.com/jesseduffield/gocui/gui.go:507 +0x33e
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00030e420, 0xc00030e420, 0x0)
        /tmp/gobuild/vendor/github.com/jesseduffield/gocui/gui.go:456 +0x247
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc00036a420, 0x0, 0x0)
        /tmp/gobuild/pkg/gui/gui.go:311 +0x2aa
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc00036a420, 0xc000312a00, 0x0)
        /tmp/gobuild/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
        /tmp/gobuild/pkg/app/app.go:54
main.main()
        /tmp/gobuild/main.go:74 +0x883
```

I'll try again in the evening. Can't use too much of my companies time on that bug.

**Comment by dawidd6** [comment]
That was an actual bug, that you found. Should be fixed now. You can test again.

**Comment by jakobkogler** [comment]
Looks good. The key combination works now, but I can't see the log anymore. The other tabs work fine (Stats, Config, Top), but the log panel stays empty. Only by pressing `m`, I can see the log.

**Comment by dawidd6** [comment]
Previously you used the binary and now you used Docker image. It is known issue, that in Docker one does not get logs and CPU usage in percentage near container name.

**Comment by jakobkogler** [comment]
Ok, then everything looks fine.
