### ISSUE TITLE
Unknown character in keybindings

### ISSUE THREAD

**Issue by mjarkk** [jesseduffield/lazydocker#16]
Wile lookin at the keybindings i found a key binding that has a unknown font character,  
See: **next tab**

![image](https://user-images.githubusercontent.com/15320763/60396403-a1213b80-9b41-11e9-8ab3-9ef67c9a975f.png)

![image](https://user-images.githubusercontent.com/15320763/60395778-d4130180-9b38-11e9-81f6-d4206d243c75.png)

### Detials:
- **os:** Solus 4 (linux)

**Comment by jesseduffield** [comment]
good pickup :) 
fixed here https://github.com/jesseduffield/lazydocker/pull/17
