### ISSUE TITLE
Two-finger scrolling on Macbook causes crash

### ISSUE THREAD

**Issue by jshahbazi** [jesseduffield/lazydocker#160]
Scrolling down in the main panel log view past the bottom with the two-finger method on Macbooks causes the app to crash when it's done too quickly.  If you swipe slowly its fine, but a quick swipe when its already at the bottom of the log will cause the app to crash with no error message.

**Comment by dawidd6** [comment]
Can you provide more info, like which terminal emulator are you using and which version of lazydocker have you installed?

**Comment by jesseduffield** [comment]
also @jshahbazi could you post the stacktrace of the error?

**Comment by jshahbazi** [comment]
It doesn't produce any sort of error or stacktrace.  It just exits immediately, sometimes with characters like this:  `65;157;25M65;157;25M65;157;25M65;157;25M65;157;25M65;157;25`

**Comment by jshahbazi** [comment]
I'm using v0.7.4 and my terminal emulator is xterm-256color

**Comment by jesseduffield** [comment]
Should be fixed on latest master
