### ISSUE TITLE
"Runtime error: invalid memory address or nil pointer dereference" while navigating

### ISSUE THREAD

**Issue by medinae** [jesseduffield/lazydocker#168]
**Describe the bug**
Golang error that stopped the execution.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x9a8 pc=0x1059375]

goroutine 1 [running]:
github.com/jesseduffield/gocui.(*View).draw(0xc0003a6500, 0xffffffffffffffff, 0xc00018d748)
	/home/circleci/project/vendor/github.com/jesseduffield/gocui/view.go:360 +0x474
github.com/jesseduffield/gocui.(*Gui).draw(0xc0002ea370, 0xc0003a6500, 0x0, 0x0)
	/home/circleci/project/vendor/github.com/jesseduffield/gocui/gui.go:750 +0xe5
github.com/jesseduffield/gocui.(*Gui).flush(0xc0002ea370, 0x0, 0x0)
	/home/circleci/project/vendor/github.com/jesseduffield/gocui/gui.go:535 +0x1ef
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0002ea370, 0xc0002ea370, 0x0)
	/home/circleci/project/vendor/github.com/jesseduffield/gocui/gui.go:456 +0x247
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc00035a580, 0x0, 0x0)
	/home/circleci/project/pkg/gui/gui.go:310 +0x2db
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc00035a580, 0xc0002ee9b0, 0x0)
	/home/circleci/project/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/home/circleci/project/pkg/app/app.go:54
main.main()
	/home/circleci/project/main.go:74 +0x883
```
**To Reproduce**
Cannot reproduce, but i was just navigating from Menus to Menus (logs, stats...), and from services to services.

**Expected behaviour**
Normal behaviour.

**Screenshots**

![image](https://user-images.githubusercontent.com/15857322/64588040-46faed00-d3b2-11e9-987c-020a2ad355bf.png)

**Desktop (please complete the following information):**
 - OS: MacOS X Mojave
 - Lazydocker Version v0.7.4

**Comment by jesseduffield** [comment]
looks like when we reference `v.viewLines` in line 360 of `view.go` the view no longer exists, probably because it was a menu that closed or something like that. Though we don't actually delete views, we just remove them from the global view array in `DeleteView()`. So I'm not sure what's going on here. Does anybody have ideas?

**Comment by jesseduffield** [comment]
This should now be resolved because we no longer delete any views (or remove them from the global view array) as of https://github.com/jesseduffield/lazydocker/pull/372
