### ISSUE TITLE
Double entry in menu

### ISSUE THREAD

**Issue by Tset-Noitamotua** [jesseduffield/lazydocker#169]
**Describe the bug**
`run predefined custom command` entry appears twice in menu

**To Reproduce**
1. start lzd as container
2. press `x` on keyboard to open menu

**Expected behaviour**
one entry for c is enough

**Screenshots**
![image](https://user-images.githubusercontent.com/5635462/64672846-ee3c5a80-d46c-11e9-9b6f-c1d732317d65.png)

**Desktop (please complete the following information):**
 - OS: Linux (Deepin 15.11)
 - Lazydocker Version v0.7.4

**Comment by dawidd6** [comment]
Thanks for reporting this.
