### ISSUE TITLE
Display only some information's block on start

### ISSUE THREAD

**Issue by pleminh** [jesseduffield/lazydocker#178]
Hi, 

How can i disable some information's block on start ? 
Example : I want to disable The Block Standalone Containers and Images.

Thanks

**Comment by jesseduffield** [comment]
If your concern is that these take up too much space, as of https://github.com/jesseduffield/lazydocker/pull/372 you can now increase the size of your selected panel, and you can also configure the panel to take up more space in an accordion-like effect with `gui.expandFocusedSidePanel: true`

**Comment by jesseduffield** [comment]
I'm gonna close this off but let me know if the solution doesn't satisfy your needs
