### ISSUE TITLE
Collapsible Left Panel

### ISSUE THREAD

**Issue by timc13** [jesseduffield/lazydocker#180]
**Is your feature request related to a problem? Please describe.**
Often, I just want to monitor logs for the current container

**Describe the solution you'd like**
A hotkey to collapse the left side panel (Project, Containers, Images, Volumes).  Perhaps this collapsed view can be borderless (except the top border which could still have the tabs).  In this collapsed mode, the top border could also include a label indicating the current container

**Describe alternatives you've considered**
None

**Comment by mjarkk** [comment]
Agree,  
Beside that if the terminal it too thin it's also annoying to read the logs, it also would be nice if lazydocker changes to some kind of small mode where the user can toggle between the menus and information.

**Comment by dilantha** [comment]
Would be nice to have a configurable left panel width as well.

**Comment by mjarkk** [comment]
Maybe something like `[` and `]` to change the width

**Comment by jesseduffield** [comment]
This is addressed in https://github.com/jesseduffield/lazydocker/pull/372
