### ISSUE TITLE
User friendly output if docker is not running

### ISSUE THREAD

**Issue by reicheltp** [jesseduffield/lazydocker#188]
**Is your feature request related to a problem? Please describe.**
If you run `lazydocker` but docker engine is not started, you get a weird error output:

```
2019/11/12 09:33:42 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues     
*errors.withStack error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
/home/circleci/project/main.go:88 (0x8b2d31)
/usr/local/go/src/runtime/proc.go:200 (0x4305fc)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x458781)
```

For a "casual" docker user it is not clear on the first sight that docker is not running.

**Describe the solution you'd like**
As a user I would like to see a straight message, that `lazydocker` can not connect to docker and I would like to receive a hint that docker is not yet started.

```
Error: Could not connect to docker!

In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

For a detailed error message a `--verbose` flag would be a good idea.

**Describe alternatives you've considered**
Keep it as it is.

**Additional context**

**Comment by jesseduffield** [comment]
Fixed on latest master
