### ISSUE TITLE
Option to hide timestamps or change formatting

### ISSUE THREAD

**Issue by marcosfede** [jesseduffield/lazydocker#193]
**Is your feature request related to a problem? Please describe.**
Log Timestamps take a lot of space in the UI, It would be nice to have an option to hide them, or change their format

**Describe the solution you'd like**
A config to hide timestamps

**Comment by jesseduffield** [comment]
Agreed: there should be a keybinding for toggling timestamps while the main panel is focused. 't' would do fine.

**Comment by jesseduffield** [comment]
On master you can now hide timestamps via:
```yaml
logs:
  timestamps: true
  since: '60m'
```

Closing
