### ISSUE TITLE
add search to the panel

### ISSUE THREAD

**Issue by Hongjinpin** [jesseduffield/lazydocker#195]
**Is your feature request related to a problem? Please describe.**
I hope be able to add search to the panel, I might prefer to use terminal commands when there are too many containers running and it is difficult to find the one or several of them

**Describe the solution you'd like**
Hope to achieve similar commands  
- docker ps |grep xxx  
- docker ps container_id
volume Same as above

**Comment by lingster** [comment]
I'd second this suggestion and maybe perhaps we can use less/vim like bindings for search. So for example in the config view, you can press `/` and that would be the same as seaching in vim/less

**Comment by fredericrous** [comment]
I'm using docker swarm. I have loads of containers. The order of the container changes when one exit, is created or restart. A filter with `/` would solve this and would help find the container I'm looking for. It'd be the dream

**Comment by jesseduffield** [comment]
This is actually a feature that was added recently to lazygit, so it shouldn't be too hard to port over to lazydocker. I'm not sure I'm gonna have time in the near future to do it myself though :/

**Comment by jesseduffield** [comment]
Alright homies the time has come for me to start on this feature

**Comment by jesseduffield** [comment]
I've got a WIP PR up for this now: https://github.com/jesseduffield/lazydocker/pull/392

**Comment by lingster** [comment]
Thank you for implementing this! will update my lazydocker
