### ISSUE TITLE
Arm build fails

### ISSUE THREAD

**Issue by jgonyea** [jesseduffield/lazydocker#196]
**Describe the bug**
While attempting to build lazydocker on my Pinebook Pro, the process failed on step 11/29 with
`
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} GOARM=${GOARM}     go build -a -mod=vendor     -ldflags="-s -w     -X main.commit=${VCS_REF}     -X main.version=${VERSION}     -X main.buildSource=Docker"' returned a non-zero code: 159 `

**To Reproduce**
Cloned repo to ~/projects/lazydocker
cd to ~/projects/lazydocker

> docker build -t lazyteam/lazydocker \
> --build-arg BASE_IMAGE_BUILDER=arm64v8/golang \
> --build-arg GOARCH=arm64 \
> https://github.com/jesseduffield/lazydocker.git

As per the documentation.

**Expected behaviour**
Project to build lazydocker completely

**Logs**
rock64@pinebookpro:~/projects/lazydocker$ docker build -t lazyteam/lazydocker \
> --build-arg BASE_IMAGE_BUILDER=arm64v8/golang \
> --build-arg GOARCH=arm64 \
> https://github.com/jesseduffield/lazydocker.git
Sending build context to Docker daemon  10.72MB
Step 1/29 : ARG BASE_IMAGE_BUILDER=golang
Step 2/29 : ARG ALPINE_VERSION=3.10
Step 3/29 : ARG GO_VERSION=1.12.6
Step 4/29 : FROM ${BASE_IMAGE_BUILDER}:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
1.12.6-alpine3.10: Pulling from arm64v8/golang
54e94bcddc88: Pull complete 
43582c0db3f3: Pull complete 
9fe16242a9df: Pull complete 
fbf0f20b3a29: Pull complete 
57bbd25d50cb: Pull complete 
Digest: sha256:b8ae119005f20e1b7b158300c69a5672416f2f481bd6255ff9a09b9f36a5a933
Status: Downloaded newer image for arm64v8/golang:1.12.6-alpine3.10
 ---> 568cb09a3355
Step 5/29 : ARG GOARCH=amd64
 ---> Running in 55ea7c6f20e9
Removing intermediate container 55ea7c6f20e9
 ---> 347b546d7965
Step 6/29 : ARG GOARM
 ---> Running in c4369805d76d
Removing intermediate container c4369805d76d
 ---> 5ea8c8635af7
Step 7/29 : ARG VERSION
 ---> Running in 04537dd28b8b
Removing intermediate container 04537dd28b8b
 ---> 3181918c3010
Step 8/29 : ARG VCS_REF
 ---> Running in 75b94a716452
Removing intermediate container 75b94a716452
 ---> 07d739db17ba
Step 9/29 : WORKDIR /tmp/gobuild
 ---> Running in 737ab57c1377
Removing intermediate container 737ab57c1377
 ---> cb1d71eff896
Step 10/29 : COPY ./ .
 ---> 3c5ed7225348
Step 11/29 : RUN CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} GOARM=${GOARM}     go build -a -mod=vendor     -ldflags="-s -w     -X main.commit=${VCS_REF}     -X main.version=${VERSION}     -X main.buildSource=Docker"
 ---> Running in 98f972e12a69
The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} GOARM=${GOARM}     go build -a -mod=vendor     -ldflags="-s -w     -X main.commit=${VCS_REF}     -X main.version=${VERSION}     -X main.buildSource=Docker"' returned a non-zero code: 159

**Desktop:**
Pinebook Pro, Ubuntu Mate 18.04

`rock64@pinebookpro:~/projects/lazydocker$ cat /proc/cpuinfo `
processor	: 0
model name	: ARMv8 Processor rev 4 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv8 Processor rev 4 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv8 Processor rev 4 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv8 Processor rev 4 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

processor	: 5
model name	: ARMv8 Processor rev 2 (v8l)
BogoMIPS	: 48.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 2

**Comment by jgonyea** [comment]
Followup to this:

Building against the Armv7 works for me and my PineBook Pro.

**Comment by jesseduffield** [comment]
@jgonyea could you try this again with the latest release?

**Comment by jgonyea** [comment]
Works for me! Thanks!
