### ISSUE TITLE
Any plans on making a snappy packages? (Question)

### ISSUE THREAD

**Issue by titus-anromedonn** [jesseduffield/lazydocker#20]
Love the project, this is awesome, great job!

I was wondering, do you have any plans on making a snappy package?

**Comment by dawidd6** [comment]
If there is such demand, I could do it by directly contributing `snapcraft.yaml` to this repo.

But I would better like not to be the one who uploads to Snap store.
Definitely would be the best if the uploader was the original creator of software. @jesseduffield

**Comment by titus-anromedonn** [comment]
> If there is such demand, I could do it by directly contributing `snapcraft.yaml` to this repo.
> 
> But I would better like not to be the one who uploads to Snap store.
> Definitely would be the best if the uploader was the original creator of software. @jesseduffield
> 
> NOTE for Jesse: you already have a launchpad account so there is simply no need to make another account and Canonical provides this [service](https://build.snapcraft.io) for automatic builds straight from Github repo.

Agreed. Personally, I would prefer to have the snappy package available for download instead of having to manually download the linux binary myself, but that's just me being lazy!

**Comment by jesseduffield** [comment]
I'm happy to do this if I can get some guidance on what needs to be done :P

**Comment by dawidd6** [comment]
I'll try to tackle this today.

**Comment by dawidd6** [comment]
Seems like you are using goreleaser and it has snapcraft support:
https://goreleaser.com/customization/#Snapcraft

Maybe we should do it this way?

**Comment by dawidd6** [comment]
I made two variants:
- added snapcraft.yaml
- modified .goreleaser.yml

https://github.com/jesseduffield/lazydocker/compare/master...dawidd6:snapcraft
