### ISSUE TITLE
Exiting viewing of logs ?

### ISSUE THREAD

**Issue by iangregsondev** [jesseduffield/lazydocker#205]
Hi,

I pressed m to view my logs, and it works, it displays all the logs, but how do i exit ?

I pressed ctrl+c and various keys but it just displays weird characters - heres an example

```
➜  lightning lazydocker

+ docker-compose logs --follow loop

Attaching to lightning_loop
loop_1      | 2020-02-16 09:14:30.732 [INF] LOOPD: Version: 0.4.1-beta commit=
loop_1      | 2020-02-16 09:14:30.732 [INF] LNDC: Creating lnd connection to lnd:10009
loop_1      | 2020-02-16 13:07:22.844 [INF] LOOP: 695728 Sweep on chain HTLC to address tbphg00uygtgnd6ryj74rzdkz with fee 0.00000138 BTC (tx 9a43a78f701720c60866bfe3ab676)
^Mx^M^M^[^C:x^M^M^Mwfrwfg^M^M^[[A^[[B^C^M^M^M^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

I mustn't be doing it right :-)

But I don't see anything in the instructions..

Right now, I am unable to ctrl+c out of it or anything

**Comment by iangregsondev** [comment]
It seems it works now, I think sometimes the application enters a weird state. I re-run it and all is well

**Comment by jesseduffield** [comment]
closing due to staleness. I don't think we'll have this issue again but if anybody comes across it let me know
