### ISSUE TITLE
There was not enough window space to start the application

### ISSUE THREAD

**Issue by frakman1** [jesseduffield/lazydocker#211]
On Windows 10.

lazydocker hangs when launching and gives this error when pressing Ctl+C:

```
*errors.errorString There was not enough window space to start the application
```
### Steps to reproduce:

After after I downloaded the latest version using:
```
curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
```
Then launching from a web-terminal window to my Unraid server, I get this error.

```bash
root@Tower:~# lazydocker
^C2020/03/25 14:27:52 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*errors.errorString There was not enough window space to start the application
/home/circleci/project/vendor/github.com/jesseduffield/gocui/gui_notwin.go:57 (0x865228)
/home/circleci/project/vendor/github.com/jesseduffield/gocui/gui.go:104 (0x860f04)
/home/circleci/project/pkg/gui/gui.go:247 (0x887452)
/home/circleci/project/pkg/gui/subprocess.go:20 (0x898b8f)
/home/circleci/project/pkg/app/app.go:54 (0x8ad653)
/home/circleci/project/pkg/app/app.go:54 (0x8ad646)
/usr/local/go/src/runtime/proc.go:200 (0x42d79c)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x4585b1)
```

**Screenshots**
As you can see, it is a full screen sized terminal window:
![image](https://user-images.githubusercontent.com/5826484/77572695-cca13e80-6ea5-11ea-866e-5caa6949430e.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Lazydocker Version [0.8]

**Additional context**
Note, that this works when I connect to the server using MobaXterm on windows.

**Comment by jesseduffield** [comment]
@frakman1 could you try this again on the latest master?

**Comment by frakman1** [comment]
Yes, this works now. Thank you for the update.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/5826484/167877610-9340ff56-7194-4d41-854a-dbef4735df84.png">
