### ISSUE TITLE
White font on white background in dialogs

### ISSUE THREAD

**Issue by DannyBen** [jesseduffield/lazydocker#214]
I suggest avoiding the use of white color for dialog fonts. It is barely readable for light background users.

Screenshot:

![image](https://user-images.githubusercontent.com/2405099/79246385-e7058100-7e81-11ea-8b8d-9753dc765a0b.png)

In addition, as you can see - I am not sure why the border, when active, changes its character set.

- I looked at the [config documentation](https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md) and couldn't see anything that helps for this particular issue.
- I saw there is a closed related issue #9 
- I saw there is an open request for more color customization (#67) - and although I would also love to see it, I believe the default configuration should be plain and easy (can be achieved by just not using black and white colors).

Lastly - another small thing I wish would be different in the UI, and does not deserve its own ticket - is the fact that selected rows are just bold, and not, say green or some other color. The bold is not that different than the non-bold in some terminal fonts.

**Comment by eugenevd** [comment]
I'm using urxvt with solarized light theme and get something very similar to @dusty-phillips 
In lazygit I sorted this with lightTheme, would be nice here

**Comment by jesseduffield** [comment]
Fixed by https://github.com/jesseduffield/lazydocker/pull/362
