### ISSUE TITLE
Error response from daemon: connection refused

### ISSUE THREAD

**Issue by Digicrat** [jesseduffield/lazydocker#220]
**Describe the bug**
On OSX, after installing from Homebrew, I'm getting the error: 

"Error response from daemon: dial unix docker.raw.socket: connect: connection refused"

Sometimes it works normally after dismissing the error, other times it is unable to display any data. 

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6 (Mojave)
 - Lazydocker Version 0.8 (fresh install from homebrew)

**Comment by sdawodu** [comment]
+1

**Comment by sdawodu** [comment]
@Digicrat I think this might actually be a bug with docker desktop. I had the same, updated docker desktop to 2.3.0.2 and things appear to be more stable

**Comment by olets** [comment]
I got this with Docker Desktop Apple Silicon Tech Preview RC 1 (assuming `socket` vs `sock` is not meaningful. could be meaningful but I'm guessing the log message has changed over the past year). I've been getting a Docker Desktop (not lazydocker) bug where sometimes it hangs (menubar icon animates indefinitely) while trying to start up. This time I forgot Docker hadn't started started and ran lazydocker:

```
*errors.withStack Error response from daemon: dial unix docker.raw.sock: connect: connection refused
/<user name>/circleci/project/main.go:88 (0x14a9449)
/usr/local/go/src/runtime/proc.go:200 (0x102d1cc)
/usr/local/go/src/runtime/asm_amd64.s:1337 (0x1057ed1)
```

Sharing in case lazydocker can be taught to look for this and give a friendlier error.

**Comment by jesseduffield** [comment]
On latest master we now gracefully wait for docker to start instead of crashing. Closing
