### ISSUE TITLE
integration own commands

### ISSUE THREAD

**Issue by StephanKrauss** [jesseduffield/lazydocker#230]
Hello,

i start the lazydocker with:

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v c:/test/lazydocker:/.config/jesseduffield/lazydocker lazyteam/lazydocker

Under ' c:/test/lazydocker' is the lazydocker project.
For example the config.yml .

-----------------------
gui:
  scrollHeight: 2
  theme:
    activeBorderColor:
    - red
    - bold
    inactiveBorderColor:
    - green
    optionsTextColor:
    - white
reporting: "on"
commandTemplates:
  restartService: '{{ .DockerCompose }} restart {{ .Service.Name }}'
  dockerCompose: docker-compose
  stopService: '{{ .DockerCompose }} stop {{ .Service.Name }}'
  serviceLogs: '{{ .DockerCompose }} logs --since=60m --follow {{ .Service.Name }}'
  viewServiceLogs: '{{ .DockerCompose }} logs --follow {{ .Service.Name }}'
  rebuildService: '{{ .DockerCompose }} up -d --build {{ .Service.Name }}'
  recreateService: '{{ .DockerCompose }} up -d --force-recreate {{ .Service.Name }}'
  viewContainerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID
    }}
  containerLogs: docker logs --timestamps --follow --since=60m {{ .Container.ID }}
  allLogs: '{{ .DockerCompose }} logs --tail=300 --follow'
  viewAlLogs: '{{ .DockerCompose }} logs'
  dockerComposeConfig: '{{ .DockerCompose }} config'
  checkDockerComposeConfig: '{{ .DockerCompose }} config --quiet'
  serviceTop: '{{ .DockerCompose }} top {{ .Service.Name }}'
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []
oS:
  openCommand: open {{filename}}
  openLinkCommand: open {{link}}
update:
  dockerRefreshInterval: 100ms
stats:
  graphs:
  - caption: CPU (%)
    statPath: DerivedStats.CPUPercentage
    color: blue
  - caption: Memory (%)
    statPath: DerivedStats.MemoryPercentage
    color: green
-----------------------

Is there a way to define in the config.yml my own commands ?

I work under windows 10 and docker desktop.

**Comment by karfau** [comment]
FYI: please wrap your code snippet with triple back ticks (this one: ```), this way the whitespace will be visible which makes it easier to read the config like in an editor:

```
gui:
  scrollHeight: 2
theme:
  activeBorderColor:
	- red
	- bold
```
Since white space is very important in yaml files, it's essential to preserve them here.
(Since I don't know anything about the config file yet, I don't know if my example is correct. If in doubt copy paste from your file again.)

**Comment by StephanKrauss** [comment]
Hello,

i have found a config file for lazydocker. In this config file ther is a part
for custom commands. 

```
customCommands:
  containers:
  - name: bash
    attach: true
    command: docker exec -it {{ .Container.ID }} /bin/sh
    serviceNames: []  
```

In this part i will define my own commands.
Where can i find information about the syntax for my commands.
I will buid a command to see the enviroments params of a container.

The docker command is: docker inspect <docker-hash or docker-name>

I would be grateful for any information.

Best regards

Stephan

**Comment by karfau** [comment]
Did you see that beside the log tab on the left side there is also a "Container Config" tab?
If you scroll down in it the full response if docker inspect is already available for immediate inspection, without the need to "switch screen" or add custom command

![image](https://user-images.githubusercontent.com/135657/92100894-a5e41e00-eddc-11ea-9c7e-50f0fd32ff30.png)

**Comment by StephanKrauss** [comment]
In lazydocker in the container configs i missing the part 'env' . 
We start the docker-compose with same env params. 
When i call in the console docker inspect <myDocker> , i see the env params but not in lazydocker.

```
 "Config": {
            "Hostname": "e354040fbf71",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "app_name=XXXX",
                "ORY_TOKEN_NAME=XXXX",
                "AUTH_BASE_URL=https://10.10.10.10",
                ...

```

Your sincerly 

Stephan

**Comment by karfau** [comment]
Your last comment totally qualifies for a bug report or feature request. :)
(I didn't find any related issues that would indicate why those are missing.)

Not sure if you want to create it as an extra issue or change this one.

**Comment by StephanKrauss** [comment]
Hello,

can you please write this as a new feature. My English is not that good. This feature is important to me. I work with docker-compose. The environment parameters are transferred to docker-compose. It is important to control these parameters in lazydocker.

Best regards

Stephan

**Comment by karfau** [comment]
Controlling them is not something that is inside the scope of lazydocker I think, but seeing them should be doable I hope.

You can just create a new issue using the text in [your comment](https://github.com/jesseduffield/lazydocker/issues/230#issuecomment-686410632), it contains everything it needs.

(And just to clarify: I don't have write access to this repo, only like the tool and offering some help here.)

**Comment by StephanKrauss** [comment]
Hello,

the solution is simple.
Edit config.yml
```
customCommands:
  containers:
  - name: enviroments var
    attach: true
    command: docker inspect {{ .Container.ID }}
    serviceNames: []
```

Your sincerly

Stephan

**Comment by jesseduffield** [comment]
Closing this because it looks like it's resolved. Let me know if that's not the case
