### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by tuxpeople** [jesseduffield/lazydocker#236]
I'm currently working on packaging lazydocker for Alpine Linux.

**Describe the bug**
go test fails:

```
# github.com/jesseduffield/lazydocker/pkg/gui
pkg/gui/keybindings.go:56:9: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/gui/volumes_panel.go:100:57: conversion from int64 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

**To Reproduce**
1. GOPATH="$srcdir" go build
2. GOPATH="$srcdir" go test ./...

$srcdir is where the extracted tar.gz is.

**Expected behaviour**
Tests succeeding

**Desktop (please complete the following information):**
 - OS: Alpine
 - Lazydocker Version v0.9

In the meantime, I'll deactivate the tests.

**Comment by jesseduffield** [comment]
Apologies for the late reply @tuxpeople , is this still a problem?

**Comment by tuxpeople** [comment]
Hi @jesseduffield no worries. I don't know tbh, need to check. I'm on vacation this week without my laptop. It will be next week till I can check that.

**Comment by omnivagant** [comment]
The tests that are ran seem to run fine now, see https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/40097

**Comment by jesseduffield** [comment]
Sweet :) I'll close this off. Thanks @omnivagant
