### ISSUE TITLE
Missing container information

### ISSUE THREAD

**Issue by teawithfruit** [jesseduffield/lazydocker#239]
**Describe the bug**
After the last Docker Update on Mac OS, all the information on the right side of lazydocker are not visible anymore.

**To Reproduce**
Just open lazydocker with the latest Docker Version (2.3.0.5).

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/489877/94412789-85f50f80-017a-11eb-9051-6198b0fa2ce8.png)

**Desktop:**
 - OS: MacOS 10.15.6
 - Lazydocker Version 0.9.1

**Comment by MonksterFX** [comment]
Same over here

**Comment by lubbyhst** [comment]
Same here
Docker Enginge: 19.03.13
Compose: 1.27.4
MacOS: 10.15.6
LD: 0.9

**Comment by sfragata** [comment]
LD version
```
Version: 0.9
Date: 2020-05-28T02:55:29Z
BuildSource: binaryRelease
Commit: 10617da5608990bf4911142745d31566bac6964a
OS: darwin
Arch: amd64
```

Docker version 19.03.13, build 4484c46d9d

Docker desktop version: 2.4.0.0(48506)

**Comment by zethnest** [comment]
Is it only logs? Or does `Stats` , `Config` and `Top` does not produce any output too?

**Comment by teawithfruit** [comment]
Stats, Config and Top are also empty.

**Comment by Fed03** [comment]
👍  same here

Lazydocker version 0.9.1
Docker version 19.03.13
Docker desktop version: 2.4.0.0(48506)

**Comment by restagner** [comment]
I am seeing the same issue regardless of Lazydocker version. I've seen this with

- Lazydocker version 0.9.1
- Lazydocker version 0.7.6

I am running Docker Desktop (version 2.4.0.0) on MacOS (version 10.14.6 -- Mojave). Not being able to review the logs within a central location (like lazydocker) makes using lazydocker less attractive :-(

**Comment by fakofsky** [comment]
same here
- Lazydocker Version: 0.9.1
- Docker Desktop (version 2.4.0.0) on MacOS
- Docker version 19.03.13, build 4484c46d9d

**Comment by MistaTwista** [comment]
Looks like mine, logs hiding while switch containers in app, after quit - message "Waited three seconds for child process to stop. There may be an orphan process that continues to run on your system.".

**sysinfo:**
lazydocker installed from brew
lazydocker: stable 0.9.1 (bottled)
Docker Desktop 2.4.0.0 (48506), engine 19.03.13

**Comment by sfragata** [comment]
there is  a PR to fix this problem
https://github.com/jesseduffield/lazydocker/pull/241
