### ISSUE TITLE
README does not specify XCode requirements

### ISSUE THREAD

**Issue by john20xdoe** [jesseduffield/lazydocker#24]
When using brew to install, I'm getting this error:
```
$ brew install lazydocker
==> Installing lazydocker from jesseduffield/lazydo
Error: Your Xcode (10.0) is too outdated.
Please update to Xcode 10.2.1 (or delete it).
Xcode can be updated from the App Store.

Error: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install
```
OS: MacOS Mojave.
I have an XCode 10.0, and cannot delete it (using it for development), or upgrade it yet (company-managed software).

I would like to confirm if the above version is really needed by lazydocker before I badger our IT services about an upgrade 😃 .

If so, shouldn't it be in the README as well?

**Comment by justintien** [comment]
@john20xdoe 
You can try this:
```sh
xcode-select --install
# mac will popup xcode install interface to confirm

brew install lazydocker
```

**Comment by john20xdoe** [comment]
Hi @justintien , thanks for the reply. I haven't tried it with my XCode 10.0 since I found I already have XCode 10.2.1, but it was not named XCode.app.

I swapped their names in my Applications folder. 10.2.1 to XCode.app, while the 10.0 to XCode 10.0.

But I did run `xcode-select --install` after the rename, and `brew install lazydocker` is now working.
