### ISSUE TITLE
Log panel doesn't update after Docker Desktop Community 2.3.0.5

### ISSUE THREAD

**Issue by dilantha** [jesseduffield/lazydocker#240]
I upgraded to Docker Desktop Community 2.3.0.5 and 2.4.0.0 I noticed the right hand panel doesn't update when switching services.

- OS: macOS Catalina 10.15.5
- Lazydocker version 0.9.1

**Comment by deejayres** [comment]
I am having the same issue on:
• Lazydocker 0.9.1
• Docker Desktop Community 2.4.0
• macOS Cataline 10.15.7

**Comment by restagner** [comment]
I am seeing the same issue regardless of Lazydocker version. I've seen this with
- Lazydocker version 0.9.1 
- Lazydocker version 0.7.6

I am running Docker Desktop (version 2.4.0.0) on MacOS (version 10.14.6 -- Mojave).  Not being able to review the logs within a central location (like lazydocker) makes using lazydocker much less attractive :-(

**Comment by lstolcman** [comment]
Duplicate of #218 too - I have the same problem.
PR #241 fixes the problem (you can test it by cloning the repo, applying a patch and running: `go run main.go`)

**Comment by butsjoh** [comment]
Any new release planned that would fix this issue?

**Comment by sfragata** [comment]
:cricket: :cricket: :cricket:

**Comment by jacobgoh101** [comment]
this seems to have been fixed in the latest release v0.10 https://github.com/jesseduffield/lazydocker/releases/tag/v0.10

**Comment by dilantha** [comment]
Yes I've checked and the logs are visible now.
