### ISSUE TITLE
error on alacritty bug

### ISSUE THREAD

**Issue by mohammad-safakhou** [jesseduffield/lazydocker#242]
i installed it via go get
and im using alacritty
when i want to run it this error occurred:

*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
/home/mohammad/go/src/github.com/jesseduffield/lazydocker/main.go:88 (0x8bdaa8)
	main: newErr := errors.Wrap(err, 0)
/usr/local/go/src/runtime/proc.go:204 (0x439c09)
	main: fn()
/usr/local/go/src/runtime/asm_amd64.s:1374 (0x46c641)
	goexit: BYTE	$0x90	// NOP

**Comment by jesseduffield** [comment]
Fixed on latest master
