### ISSUE TITLE
Does your Machine's Fan Go crazy every time you forget the lazydocker running ?

### ISSUE THREAD

**Issue by AhmedKamal20** [jesseduffield/lazydocker#249]

**Comment by breml** [comment]
My fan does not really going crazy, but I observe a constant cpu usage of a round 7% (on a Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz) by lazydocker as well, even if everything else is idling (no containers are running). So I also suspect, that lazydocker does more than necessary.

**Comment by mfn** [comment]
I can't confirm the fan going crazy (there's so much stuff going on on my work machine), but the CPU usage is constantly hovering around 10% even, just by starting lazydocker and not interacting with it and having no docker containers running (only "exit"ed once shown):
![image](https://user-images.githubusercontent.com/87493/105173881-f822a300-5b21-11eb-9ec2-717d284ee85d.png)


When I shutdown Docker for Desktop completely and leave lazydocker running, it seems to consume 2/3% of CPU (can't start lazydocker when Docker for Desktop isn't running).

**Comment by mfn** [comment]
Darn, forgot my specs 😅 MacBook Pro (16-inch, 2019) 2,4 GHz 8-Core Intel Core i9

**Comment by lemmy04** [comment]
I'm seeing around 2.5% cpu use on a i5 with no actual containers running.

**Comment by thekashifmalik** [comment]
I was seeing high CPU load on a machine I left `lazydocker` running on overnight. I thought it was from the Elasticsearch service but `htop` showed `lazydocker` with consistently high CPU usage. Load dropped instantly after killing the process.

I'm a big fan of this tool so would love to figure out where the high CPU usage is coming from.

Wonder if it has to do with log outputs.

**Comment by jesseduffield** [comment]
I also find my fan goes a bit crazy sometimes, though my prior debugging efforts proved useless. Happy to accept a PR taking a stab at the problem

**Comment by jesseduffield** [comment]
The latest release should fix this issue: https://github.com/jesseduffield/lazydocker/releases/tag/v0.17.1

I'll close this off but let me know if the issue persists and I'll reopen
