### ISSUE TITLE
MacOS 10.14.5 - Can't copy text from application

### ISSUE THREAD

**Issue by Doppelfrog** [jesseduffield/lazydocker#25]
It doesn't appear possible to copy text from within the lazydocker terminal windows:  Mouse click and select does nothing.

lazydocker is running in default Terminal.

**Comment by jesseduffield** [comment]
you will need to hold 'option' while dragging your mouse (assuming you're on a mac). Reason being that in order to receive click events, we need to hold option to communicate that we're not actually trying to click something

**Comment by jesseduffield** [comment]
closing, as I've now added this to the [FAQ](https://github.com/jesseduffield/lazydocker#faq)
