### ISSUE TITLE
homebrew formula breaks homebrew cleanup

### ISSUE THREAD

**Issue by olets** [jesseduffield/lazydocker#253]
**Describe the bug**

Having lazydocker installed breaks Homebrew's cleanup process.

**To Reproduce**

1. Install lazydocker
2. Run `brew doctor`

**Expected behaviour**

I can run `brew upgrade` after using Homebrew to install lazydocker.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS:
    macOS
 - Lazydocker Version
    0.12
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)
     I installed with Homebrew

**Additional context**

More details at https://github.com/Homebrew/discussions/discussions/1413#discussioncomment-699179

**Comment by jesseduffield** [comment]
with the latest release, brew doctor works fine for me. I'll close this off but let me know if you still have the issue and I'll reopen
