### ISSUE TITLE
Command Line option/argument for connecting to a remote docker host

### ISSUE THREAD

**Issue by strenic** [jesseduffield/lazydocker#255]
There doesn't seem to be an easy way right now to run lazydocker on my local pc and monitor my docker containers on a remote host.  Could an argument be added to point lazydocker to another host than my localhost?  Something like `lazydocker --host <hostname>`.  I've really enjoyed using lazydocker and this would make it even a better experience.

**Comment by volkflo** [comment]
Would be a really cool feature :)

**Comment by dvjones89** [comment]
Hi @strenic 👋  Have you taken a look at `docker-machine`? As I understand it, it allows you to point your local Docker client at a remote Docker engine, after which the usual commands such as `docker ps` and `docker images` are run against the remote host. Assuming `lazygit` is ultimately talking to the regular `docker` client on your computer, installing and configuring `docker-machine` to connect to a remote host might "just work" with `lazydocker`.

https://docs.docker.com/machine/

**Comment by strenic** [comment]
@dvjones89 That sounds interesting- I'll take a look at that.  Thanks!

**Comment by nrigaudiere** [comment]
@dvjones89 I can confirm that`docker-machine` is working alongside lazydocker using `eval $(docker-machine env <machine>)`. But the only issue is that `docker-machine` has been deprecated and is not maintained by the Docker community anymore.
