### ISSUE TITLE
Installed lazydocker by 'brew tap jesseduffield/lazydocker' on macos, but can't find it.

### ISSUE THREAD

**Issue by wzlee** [jesseduffield/lazydocker#26]
![image](https://user-images.githubusercontent.com/4182865/60405711-98357600-9be4-11e9-8213-e1b12531b617.png)

**Comment by mway** [comment]
You still need to `brew install lazydocker` after tapping `jesseduffield/lazydocker`. :)

**Comment by tamtran-agilityio** [comment]
brew install lazydocker    
```
==> Installing lazydocker from jesseduffield/lazydocker
==> Downloading https://github.com/jesseduffield/lazydocker/releases/download/v0.2.4/lazyd
Already downloaded: /Users/tamtran/Library/Caches/Homebrew/downloads/5178d89052a0a920623c3d351d7135a9ac82ac50d26006fb758d6db8774ed448--lazydocker_0.2.4_Darwin_x86_64.tar.gz
Error: parent directory is world writable but not sticky
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/tmpdir.rb:93:in `mktmpdir'```

**Comment by hugofcampos** [comment]
Does not seem a lazydocker problem for me. I suggest to run a brew doctor to check if there is something wrong.

**Comment by jesseduffield** [comment]
Closing as it a appears this is not an issue with lazydocker, and our readme does specify that you must to the install step after the tap step
