### ISSUE TITLE
LazyDocker does not show all images

### ISSUE THREAD

**Issue by MiroslavMikus** [jesseduffield/lazydocker#260]
**Describe the bug**
`docker images` shows more images than lazy-docker

**To Reproduce**
1. pull image from private repository
2. run `docker images`

**Expected behaviour**
lazy-docker should show all images from `docker images` list

**Screenshots**
![image](https://user-images.githubusercontent.com/29312172/121902887-08812780-cd28-11eb-8777-4b66fd04ca8e.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019. **It works on on windows 10**
 - Lazydocker Version 0.12

**Comment by dvjones89** [comment]
Hi @MiroslavMikus 👋  Forgive me if I'm telling you something you already know, but have you tried giving focus to the "images" pane within `lazydocker` and then pressing the "up" and "down" arrows on your keyboard? The pane is scrollable, though it's perhaps not immediately obvious from the user interface, hence my question.

**Comment by MiroslavMikus** [comment]
@dvjones89 Hey, good point! Hmm... tried again with the same result:
![image](https://user-images.githubusercontent.com/29312172/122547962-0de4b780-d031-11eb-8418-e6631a180c12.png)

**Comment by VProfirov** [comment]
Lazydocker doesn't refresh for new images - created after starting the lazydocker.

Can this be quickly fixed as it is for containers?

Thank you in advance! Great tool, thank you for which! :)

**Comment by jesseduffield** [comment]
@VProfirov that should be an easy fix. Happy to accept a PR for this, and give any guidance needed

**Comment by glendsoza** [comment]
Here is a PR which tries to add this functionality https://github.com/jesseduffield/lazydocker/pull/299
