### ISSUE TITLE
docker-compose build fail

### ISSUE THREAD

**Issue by xnng** [jesseduffield/lazydocker#262]
**Describe the bug**
docker-compose build fail

```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIUV0ybH/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38936252/123398882-984f8d00-d5d6-11eb-9a22-84fb141d914d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - docker: 20.10.7

**Comment by apmillen** [comment]
Having the same issue. Any workaround for this?

**Comment by jesseduffield** [comment]
Is this still an issue on the latest release @apmillen @xnng ?

**Comment by peeter123** [comment]
Looks like a docker-compose issue: https://stackoverflow.com/questions/66579446/error-executing-docker-compose-building-webserver-unable-to-prepare-context-un

**Comment by jesseduffield** [comment]
Does the issue go away if we set the following in the config:
```yaml
commandTemplates:
  dockerCompose: "docker compose"
```
If so, this will be fixed by https://github.com/jesseduffield/lazydocker/issues/371

**Comment by jesseduffield** [comment]
At any rate, given that this is not an issue with lazydocker, I'll close this issue
