### ISSUE TITLE
Add `docker-compose` binary to the docker image

### ISSUE THREAD

**Issue by ykis-0-0** [jesseduffield/lazydocker#264]
When I use the docker image provided, `lazydocker` can not detect the existence of `docker-compose.yml` even when I bind-mounted the project directory to the container like this:
```sh
docker build -t lazyteam/lazydocker \
  --build-arg BASE_IMAGE_BUILDER=arm64v8/golang \
  --build-arg GOARCH=arm64 \
  https://github.com/jesseduffield/lazydocker.git

docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/.config/lazydocker:/.config/jesseduffield/lazydocker \
  -v [PROJECT DIRECTORY HERE]:/docker-compose
  --workdir "/docker-compose/"
  lazyteam/lazydocker
```

It turns out that the cause of this situation is `docker-compose` is not included in the image built, therefore by adding that it things should work as expected.

**Describe the solution you'd like**

Add `docker-compose` to the `lazyteam/lazydocker` image.

**Additional context**

I have tried add the binary by myself, although it doesn't look good when building, it may serve some purposes so I am attaching it here: https://github.com/ykis-0-0/lazydocker/commit/2cf8335531a26027878c4f4500eff02de2779458

**Comment by jesseduffield** [comment]
Once we switch to using `docker compose` instead of `docker-compose` (see https://github.com/jesseduffield/lazydocker/issues/371) this won't be necessary.

You can also currently configure lazydocker to use `docker compose` in the config. I'll close this off. Let me know if I've missed anything
