### ISSUE TITLE
Lazydocker fails to connect in WSL to Docker.

### ISSUE THREAD

**Issue by ghost** [jesseduffield/lazydocker#266]
**Describe the bug**
When Lazydocker is run in WSL, it fails to connect to Docker.

**To Reproduce**
1. Install WSL.
2. Enable WSL 2.
3. Install [Ubuntu](https://www.microsoft.com/store/productId/9NBLGGH4MSV6) from Microsoft store.
4. Install Docker as explained in this [guide](https://dev.to/bowmanjd/install-docker-on-windows-wsl-without-docker-desktop-34m9).
5. Launch docker manually via typing `sudo dockerd` .
6. Open a new WSL window.
7. Install Lazydocker via [the binary release](https://github.com/jesseduffield/lazydocker#binary-release-linuxosxwindows).
8. Try to launch Lazydocker with `lazydocker` from any shell in WSL.

**Expected behaviour**
Lazydocker should connect to Docker and function normally.

**Screenshots**
[Link to the images](https://imgur.com/a/BMx6cGR)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 (OS Build 19043.1165)
 - Lazydocker Version: v0.12 binaryRelease (6fd5337cc272289463eb562606e67515f48b4aff)

**Additional context**
As Docker announced that they will put Docker Desktop behind a paywall for larger organizations, and my organization uses Windows as their official development platform I installed Docker in WSL. The installation worked fine and I can use Docker from the CLI, but Lazydocker speeds up the workflow by a lot. I've used it for quite a long time now with Docker Desktop and I hoped to use it in WSL as well. It seems that there is either a misconfiguration or the two are just not compatible, so I filed this bug report as the most sensible option.

**Comment by clemthi** [comment]
(Sorry for late answer)
Did you configure dockerd to be started on WSL instance start and without password (as described in the last sections of the installation guide you refer to)?

**Comment by tuxflo** [comment]
I think this could be closed, because I'm running WLS 2 with lazydocker for about two months now without any issues. (just regular docker inside WSL, no Docker Desktop)

**Comment by jesseduffield** [comment]
Alright I'll close this off @tuxflo
