### ISSUE TITLE
Esc key to escape lazydocker

### ISSUE THREAD

**Issue by kyapwc** [jesseduffield/lazydocker#27]
I think using just `q` to quit `lazydocker` is enough, as when we focus the main panel, and want to go back, we press `Esc`, sometimes we just spam the `Esc` key and `lazydocker` gets closed due to that.

Hopefully next change can just be using `q` to `quit` lazydocker.

**Comment by jesseduffield** [comment]
Good point. There is currently a config value which allows you to get a prompt ensuring you indeed want to quit if you hit esc when at the top level:

```
confirmOnQuit: true
```

Would that satisfy your requirement?

**Comment by jesseduffield** [comment]
I think this will be solvable once we implement configurable keybindings. An empty keybinding will represent that you want a key disabled, and doing something like:
```
keybindings:
  quit: ["q"] # as opposed to quit: ["q", "KeyEsc"]
```

will satisfy this requirement. So I'm closing in favour of https://github.com/jesseduffield/lazydocker/issues/48
