### ISSUE TITLE
Duplicate timestamp from log

### ISSUE THREAD

**Issue by dmaglio** [jesseduffield/lazydocker#274]
**Describe the bug**
in the log screen the timestamp is duplicated, as shown in the screenshot

**To Reproduce**
1. Launch the application
2. select a running container
3. go to Logs

**Expected behaviour**
I would expect to see only a timestamp of the logs

**Screenshots**
![image](https://user-images.githubusercontent.com/446573/140785441-a24be78a-f1fb-4f01-916d-6fc4ac4bc4b0.png)

**Desktop (please complete the following information):**
 - OS: Fedora 35 x86_64
 - Lazydocker Version
   Version: 0.12
   Date: 2021-03-24T21:08:19Z
   BuildSource: binaryRelease
   Commit: 6fd5337cc272289463eb562606e67515f48b4aff
   OS: linux
   Arch: amd64

**Comment by jesseduffield** [comment]
This is now configurable. See https://github.com/jesseduffield/lazydocker/pull/336
