### ISSUE TITLE
error while reading terminfo data: termbox: unsupported terminal

### ISSUE THREAD

**Issue by thetic** [jesseduffield/lazydocker#283]
Failure to run in tmux (`TERM=tmux-256color`) in kitty terminal.

```text
2021/12/10 19:53:20 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*errors.errorString termbox: error while reading terminfo data: termbox: unsupported terminal
./main.go:88 (0x55bb1783d9c5)
runtime/proc.go:255 (0x55bb174686e7)
runtime/asm_amd64.s:1581 (0x55bb17496401)
```

**Desktop (please complete the following information):**

 - OS: Arch Linux
 - Lazydocker Version: 0.12
 - kitty version: 0.23.1
 - tmux version: 3.2a

**Additional context**

Similar bug and conditions: https://github.com/jesseduffield/lazygit/issues/1134

**Comment by argshook** [comment]
hello, i have the same issue, but can workaround it with

```sh
TERM=screen-256color lazydocker
```

shell alias can help hiding this, i have this in my `.zshrc`

```sh
alias lazydocker="TERM=screen-256color lazydocker"
```

thanks for the awesome `lazydocker` project!

**Comment by jesseduffield** [comment]
closing as fixed now that we're using tcell (on latest master). Let me know if the issue persists on your end and I'll reopen

**Comment by Shahin-rmz** [comment]
> closing as fixed now that we're using tcell (on latest master). Let me know if the issue persists on your end and I'll reopen

 
Hello, two years later I am using wezterm as terminal and get same error!
with terminator it works fine.

**Comment by 2dChan** [comment]
ghostty + tmux  same error

Without tmux work fine.
