### ISSUE TITLE
[Feature request] VSCode extension

### ISSUE THREAD

**Issue by DanaCoding** [jesseduffield/lazydocker#290]
**Is your feature request related to a problem? Please describe.**
Installing it alone is a bit expensive, especially for full stack developers. And it's a burden for the desktop.

**Describe the solution you'd like**
If it can be integrated into VSCode, it will be good news for developers. Very convenient for development and testing.

**Comment by jesseduffield** [comment]
I believe VSCode already has its own container management thingo. Not sure that we would gain much by adding vscode support ourselves

**Comment by jesseduffield** [comment]
closing
