### ISSUE TITLE
[Feature Request] Creating a seperate context to display just environment variables in the container panel

### ISSUE THREAD

**Issue by glendsoza** [jesseduffield/lazydocker#293]
**Is your feature request related to a problem? Please describe.**
Usually, applications running inside the docker container are configured using environment variables, hence I usually find myself checking environment variables set in the container 

Currently, if I want to see environment variables for a container I need to go to the `Config` section and looks for `Env` section

It would be great if there is a separate tab where I can just view the Environment variables 

**Describe the solution you'd like**

Something like this

![with_env](https://user-images.githubusercontent.com/95934259/148991380-17615692-29fd-499f-bd8a-e31e43407428.png)

**Describe alternatives you've considered**

**Additional context**

With some code changes, I was able to implement this feature (as shown in the screenshot above), if this gets approved would be glad to create the PR!

**Comment by jesseduffield** [comment]
I'm on board with this idea. Happy to review a PR :)

**Comment by glendsoza** [comment]
Here is the PR https://github.com/jesseduffield/lazydocker/pull/295, please let me know your thoughts on this
