### ISSUE TITLE
High CPU usage on Docker VM when lazydocker is running

### ISSUE THREAD

**Issue by danielcompton** [jesseduffield/lazydocker#296]
**Describe the bug**

When I start lazydocker against an idle macOS Docker Desktop install, CPU usage goes from ~2% to over 100%.

**To Reproduce**

This is reproducible whether "Use the new Virtualisation framework " is enabled or disabled in the Docker settings.

1. Start Docker Desktop for Mac
2. Ensure no containers are running
3. Open Activity Monitor
4. Observe CPU usage of `qemu-system-aarch64` (new Virtualisation framework disabled) or `Virtual Machine Service` (new Virtualisation framework enabled) goes to 100-200%
5. Close lazydocker
6. Wait ~10s
7. Observe CPU usage goes back to near zero

**Expected behaviour**

Low to no CPU impact from turning on lazydocker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

```shell
$ lazydocker --version
Version: 0.12
Date: 
BuildSource: homebrew
Commit: 
OS: darwin
Arch: arm64
```

**Additional context**

Setting dockerRefreshInterval didn't seem to affect the CPU usage, it was still at ~170%.

```
$ cat ~/.config/lazydocker/config.yml 
update:
  dockerRefreshInterval: 2000ms
```

**Comment by danielcompton** [comment]
This is hugely improved, thanks very much! With the new Virtualisation framework I am at ~1% CPU at idle, and ~10% with lazydocker running. With the old QEMU based virtualisation it is 1-2% CPU at idle, and 50% with lazydocker running.

Side note: It seems like (as of 10 months ago, according to Reddit) the new Virtualization framework still has a lot of work to go with disk performance: https://www.reddit.com/r/docker/comments/nha68s/macos_what_impact_does_use_new_virtualization/

**Comment by jesseduffield** [comment]
Awesome. I'll close this issue off then. There's still more gains to be made in CPU usage but I'll capture that in a separate issue

**Comment by mitchell-pioneer** [comment]
Will this ever be addressed?  If I leave lazydocker running by mistake, it eats up the entire EC2 medium instance.  Without lazydocker, running ps shows 5%, with it  75%.  Its too dangerous to use since i might leave it on. Thoughts?
