### ISSUE TITLE
Menu remains displayed after clicking outside

### ISSUE THREAD

**Issue by ed-bassett** [jesseduffield/lazydocker#30]
Steps to reproduce:

1. Select any panel on the left side
1. Press `x` to show the menu
1. Click on the panel on the right (left half of menu remains displayed over the panels on the left)

Desired behaviour:
Either menu is modal, and clicking outside should be disallowed or clicking outside is meant to close the menu, and should completely remove the menu from the screen.

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazydocker/pull/43 (I'm just going to make it that you can't click out if you have a popup panel because it may be asking you something you need to answer to continue)
