### ISSUE TITLE
Change Actively Selected Line Color

### ISSUE THREAD

**Issue by typkrft** [jesseduffield/lazydocker#304]
Is it possible to change the color of the actively selected line. It's extremely hard to see. I looked through the dock for color/text/line and other keywords to see if I could find anything, but did not. It's possible I missed something so I thought I'd post here instead of filing an bug/feature.

Thanks for the great software!

Picture for reference. 
Default Settings, Dracula theme in kitty.
<img width="2056" alt="Screen Shot 2022-01-26 at 7 11 11 PM" src="https://user-images.githubusercontent.com/12100960/151267903-925b881d-b7b5-4f5d-b228-2898942d8ca6.png">

**Comment by ThomasLachaux** [comment]
I also have the same problem with Nord Theme, and therefore, not usable. It is also discussed in the issue #243.

I wasn't able to find the code section where the selection color is applied. Does this depends from another library ?

**Comment by ThomasLachaux** [comment]
By the way, I've just forked the repo to add this option.
![reverse](https://user-images.githubusercontent.com/21559770/152845053-f4b137b8-458a-4373-ba89-2127e969baf1.png)

More info here https://github.com/jesseduffield/lazydocker/issues/243#issuecomment-1031752703

**Comment by DanielPower** [comment]
I'm also using Kitty terminal. With the Tokyo Night theme. For me it's also impossible to tell which line is selected.

**Comment by jesseduffield** [comment]
This is a solved problem in lazygit so implementing here should just be a matter of copy+pasting code (or perhaps extracting common code into a shared package).

If you look in `pkg/theme/theme.go` in https://github.com/jesseduffield/lazygit that's a good starting point.

**Comment by markhagemann** [comment]
Hey @mbwhite can you try setting `intenseTextStyle` to `bold` or `all` in your WSL2 profiles list.


![image](https://user-images.githubusercontent.com/21050889/177233457-4f7ca746-a32b-428b-8095-07b332246ae2.png)

It might complain about it not being a valid property in VSCode but it works for me and fixes the issue with lazygit / lazydocker in Windows Terminal Preview. I am not sure if this property has been brought into Windows Terminal default yet. 

![image](https://user-images.githubusercontent.com/21050889/177233626-af476d0d-4b80-457b-b025-c6520b0c8ff5.png)

This is the issue where I found the solution:

https://github.com/microsoft/terminal/issues/109

**Comment by jesseduffield** [comment]
I've made it so that the selected item has a blue background in https://github.com/jesseduffield/lazydocker/pull/372

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazydocker/pull/372 is merged to master. Let me know if you have any issues
