### ISSUE TITLE
0.13 released?

### ISSUE THREAD

**Issue by das-g** [jesseduffield/lazydocker#305]
According to [repology](https://repology.org/project/lazydocker), 0.13 has been released and is available on Homebrew and Void Linux x86_64. However, there's no 0.13 entry on https://github.com/jesseduffield/lazydocker/releases, only a [Git tag `v0.13`](https://github.com/jesseduffield/lazydocker/releases/tag/v0.13).

**Comment by krmbzds** [comment]
This also breaks [lazydocker plugin](https://github.com/comdotlinux/asdf-lazydocker) for [asdf-vm](https://github.com/asdf-vm/asdf) when `latest` version is used: `asdf install lazydocker latest`

**Comment by jesseduffield** [comment]
This should now be resolved. Let me know if that's not true and I'll reopen

**Comment by das-g** [comment]
There's still no 0.13 entry in the list of releases, it seems: https://github.com/jesseduffield/lazydocker/releases?q=0.13&expanded=true

**Comment by jesseduffield** [comment]
@das-g is there a particular reason why you want to use 0.13 compared to the latest version?

**Comment by das-g** [comment]
> @das-g is there a particular reason why you want to use 0.13 compared to the latest version?

No, I don't have such a reason and don't plan to use 0.13 now that newer versions are available. I was just reacting to

> This should now be resolved. Let me know if that's not true […]

as I thought "resolved" would mean that 0.13 would now be available like the other versions on the releases list. If 0.13 cannot appear there or if you've decided it shall not appear there, that's also fine with me.
