### ISSUE TITLE
Scrolling beyond the most recent log should not be possible

### ISSUE THREAD

**Issue by ed-bassett** [jesseduffield/lazydocker#31]
Steps for reproduction:
1. Select the `Logs` tab in the right panel
1. Scroll in the direction of the more recent log messages using either the keyboard shortcuts or the mouse.
1. Keep scrolling after the most recent message reaches the top of the screen.

Desired behaviour:
It should not be possible to scroll past the most recent log message. Probably the best option would be to limit scrolling so that the most recent message cannot move further up than the bottom of the screen, but it would also be reasonable enough to limit it so that it can't move further up than the top of the screen.

**Comment by mjarkk** [comment]
This is a problem on ever tab and it also effects scrolling side ways using the arrow keys.

**Comment by jesseduffield** [comment]
This is actually not too tricky to fix, all the code is in `scrollUpMain` and `scrollDownMain` in `pkg/gui/main_panel.go`. I'll chuck a 'good first issue' label on this

**Comment by jesseduffield** [comment]
This is done!

**Comment by jesseduffield** [comment]
Also hi @ed-bassett
