### ISSUE TITLE
Compatibility with colima

### ISSUE THREAD

**Issue by akshayamaldhure** [jesseduffield/lazydocker#311]
I've replaced Docker Desktop with [lima](https://github.com/lima-vm/lima/)/[colima](https://github.com/abiosoft/colima). All the docker cli commands work fine. However, running `lazydocker` returns this.

```
$ lazydocker
2022/02/11 10:57:31 connection to docker client failed. You may need to restart the docker client
```

I tried restarting `colima`, but no luck.

**Comment by ahvargas** [comment]
@akshayamaldhure  I found a work around .
1. Find out your local unix socket via : `docker context ls` .You need docker endpoint something like `unix:///Users/youruser/.colima/docker.sock`
2. Point `DOCKER_HOST` variable before invoking lazydocker : 
```bash
DOCKER_HOST=unix:///Users/youruser/.colima/docker.sock  lazydocker
```
3. Profit ?

**Comment by akshayamaldhure** [comment]
That works. Thanks a lot! 🙇‍♂️
