### ISSUE TITLE
Where does lazydocker obtain the "Project" string?

### ISSUE THREAD

**Issue by hugalafutro** [jesseduffield/lazydocker#314]
Hi,
I got all my docker stuff in ~/docker/[container_name] Usually I cd into a stack's subdir and then run lazydocker and it displays the subdir's name as "Project" in top left corner.

I got 1 stack (librenms) that misbehaves. When I run lazydocker in ~/docker/librenms, for split second it will show (correctly) librenms, then it will change to nextcloud. I was wondering why, where does lazydocker get this string from? I have a nextcloud stack in ~/docker/nextcloud that gets called nextcloud by lazydocker, but why would it pick the name for other directory too? Nothing in docker-compose.yml mentions nextcloud.

the docker-compose.yml in question: https://o.o5.ddns.net/yYgg4

**Comment by jesseduffield** [comment]
See the discussion in this PR thread: https://github.com/jesseduffield/lazydocker/pull/88

We're pulling that project name based on the 'com.docker.compose.project' tag from docker inspect

**Comment by hugalafutro** [comment]
I see thanks for the explanation, must've been something with the image back then, I've since moved the stack to different host and forgot about the issue. Just checked and the inspect and project name are now ok
```
pi@pi-docker:~/docker/librenms $ docker inspect librenms | grep project
                "com.docker.compose.project": "librenms",
                "com.docker.compose.project.config_files": "/home/pi/docker/librenms/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/home/pi/docker/librenms",
```
and the lazydocker project name comes up as librenms
