### ISSUE TITLE
Add config to hide Docker repo prefix from image names

### ISSUE THREAD

**Issue by danielcompton** [jesseduffield/lazydocker#316]
**Is your feature request related to a problem? Please describe.**

We use ECR for our docker images. The Docker repo URL for an image is in the format `123456789012.dkr.ecr.us-east-1.amazonaws.com/<repo>`. This long prefix pushes the rest of the UI off the screen.

**Describe the solution you'd like**

A config option where we could replace a substring in the Docker image name. It would allow something like:

```yaml
replacements:
  - "123456789012.dkr.ecr.us-east-1.amazonaws.com": "<prod>"
  - "923456789999.dkr.ecr.us-east-1.amazonaws.com": "<dev>"
```

**Describe alternatives you've considered**

Not sure? Use Dockerhub?

**Additional context**

![CleanShot 2022-03-23 at 14 37 37@2x](https://user-images.githubusercontent.com/811954/159604740-7acd1bce-296c-4a6e-9b47-426ce88377f1.png)

**Comment by jesseduffield** [comment]
This should be fairly straightforward to implement so I'm chucking a 'good-first-issue' label on it. If anybody wants to take a stab and needs some pointers let me know!
