### ISSUE TITLE
Show container ports

### ISSUE THREAD

**Issue by peterkracik** [jesseduffield/lazydocker#319]
**Is your feature request related to a problem? Please describe.**
I would like to see ports of running containers.

**Describe the solution you'd like**
It would be nice to have an additional column in the Containers or Services panel to show internal/exposed ports. I guess it wouldn't be a problem to implement, maybe a little bit tricky from the UI pov, as there's not much room for that in the containers panel.

**Describe alternatives you've considered**
I don't see any alternative at the moment, either I have to run `docker ps` or check the docker-compose config

huge thanks for this tool 👍

**Comment by jesseduffield** [comment]
https://github.com/jesseduffield/lazydocker/pull/372 is merged to master. Let me know if you have any issues
