### ISSUE TITLE
Homebrew tap syntax deprecation:  lazydocker: Calling bottle :unneeded is disabled! There is no replacement.

### ISSUE THREAD

**Issue by trinitronx** [jesseduffield/lazydocker#320]
**Describe the bug**
This repo's Homebrew tap appears to be broken due to a deprecated syntax: `bottle :unneeded`

**To Reproduce**
1. Run '`brew tap  jesseduffield/lazydocker`'
2. See error:

```
    ---- Begin output of /usr/local/bin/brew tap  jesseduffield/lazydocker  ----
    STDOUT: 
    STDERR: ==> Tapping jesseduffield/lazydocker
    Cloning into '/usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazydocker'...
    Error: Invalid formula: /usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazydocker/lazydocker.rb
    lazydocker: Calling bottle :unneeded is disabled! There is no replacement.
    Please report this issue to the jesseduffield/lazydocker tap (not Homebrew/brew or Homebrew/core):
      /usr/local/Homebrew/Library/Taps/jesseduffield/homebrew-lazydocker/lazydocker.rb:9
    
    Error: Cannot tap jesseduffield/lazydocker: invalid syntax in tap!
    ---- End output of /usr/local/bin/brew tap  jesseduffield/lazydocker  ----
    Ran /usr/local/bin/brew tap  jesseduffield/lazydocker  returned 1
```

**Expected behaviour**

Homebrew's `brew tap` command should succeed and install the tap.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Lazydocker Version: Any / latest via Homebrew Tap
 - The last commit id: [`6af9e54491a989f333a8987e3ac986c2c055844a`](https://github.com/jesseduffield/lazydocker/commit/6af9e54491a989f333a8987e3ac986c2c055844a)

**Additional context**

Homebrew has deprecated the `bottle :unneeded` syntax.  Suggest removing this.

**Comment by trinitronx** [comment]
Note:  This project appears to be using GoReleaser to generate the Homebrew Tap ruby syntax.  This has been fixed upstream in GoReleaer: goreleaser/goreleaser#2595

**Comment by jesseduffield** [comment]
This is now resolved
