### ISSUE TITLE
Manually difine docker.sock location

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [jesseduffield/lazydocker#321]
**Is your feature request related to a problem? Please describe.**
I am running docker binnery with arm64 termux and installed lazydocker with go install and i can run lazydocker it self but my docker.sock is running on different folder then default /var/run/docker.sock so it is giving error 
How can i connect with manual volume ?
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skanehira** [comment]
@Morakhiyasaiyam 
You can specify socket path with `DOCKER_HOST` :)

```sh
DOCKER_HOST=unix:///var/run/docker.sock lazydocker
```

**Comment by Morakhiyasaiyam** [comment]
> @Morakhiyasaiyam You can specify socket path with `DOCKER_HOST` :)
> 
> ```shell
> DOCKER_HOST=unix:///var/run/docker.sock lazydocker
> ```

Thanks for your reply
I just used " mount -bind " and bind that my modified /var/run folder to official folder location and everything worked great 
And I can confirm that lazydocker can work on termux but ui is little messy

**Comment by jesseduffield** [comment]
Sounds like this is good to close. Lemme know if that's not true
