### ISSUE TITLE
 CPU Usage

### ISSUE THREAD

**Issue by fcsgehrke** [jesseduffield/lazydocker#323]
![image](https://user-images.githubusercontent.com/5633256/163870647-2323c6cd-34df-4bc3-8c69-101bb94b1846.png)

**Comment by fcsgehrke** [comment]
Why all this CPU usage ? 60% all the time. 

Running Linux Mint 20.3.

**Comment by jesseduffield** [comment]
PR soon to be merged https://github.com/jesseduffield/lazydocker/pull/324

**Comment by jesseduffield** [comment]
closing now that https://github.com/jesseduffield/lazydocker/releases/tag/v0.17.1 is out. Let me know if the issue persists
