### ISSUE TITLE
Arm build not working anymore

### ISSUE THREAD

**Issue by jwesemann** [jesseduffield/lazydocker#327]
**Describe the bug**
Following the build instructions directly from the git-repo as described in Readme.MD -> Docker -> "Click if you have an ARM device" fails on rapsberry pi with error message

`Sending build context to Docker daemon  11.22MB
Step 1/29 : ARG BASE_IMAGE_BUILDER=golang
Step 2/29 : ARG ALPINE_VERSION=3.10
Step 3/29 : ARG GO_VERSION=1.18
Step 4/29 : FROM ${BASE_IMAGE_BUILDER}:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder
manifest for arm64v8/golang:1.18-alpine3.10 not found: manifest unknown: manifest unknown`

**To Reproduce**
1. Start command as described in Rademe.MD `docker build -t lazyteam/lazydocker \
--build-arg BASE_IMAGE_BUILDER=arm64v8/golang \
--build-arg GOARCH=arm64 \
https://github.com/jesseduffield/lazydocker.git`
2. build starts successfully for steps 1-3
3. build fails at step 4
4. See error above in "bug description"

**Expected behaviour**
docker build command to run successfully and creating a new  local docker image

**Screenshots**
console content provided in bug dexcription

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS V11 (Bullseye) most current version as of 20220509
 - Lazydocker Version [e.g. v0.17.1.]
 - build directly from git-repo no local clone

**Additional context**

**Comment by jesseduffield** [comment]
hmm looks like there's no docker image for go 1.18 yet?

**Comment by paper42** [comment]
> hmm looks like there's no docker image for go 1.18 yet?

There is one, but not for alpine 3.10, it will have to be updated to 3.15.

**Comment by jesseduffield** [comment]
Thanks, I'll fix that up now

**Comment by jesseduffield** [comment]
Should be good now, could you confirm @paper42 @jwesemann ?

**Comment by jesseduffield** [comment]
No worries :) closing
