### ISSUE TITLE
provide left/right scrolling in logs window with mouse or provide optional wrapping

### ISSUE THREAD

**Issue by alexandervanhecke** [jesseduffield/lazydocker#34]
Hi, first of all, great tool.

I'm using lazydocker on MacOS.

mouse scrolling is possible in up / down direction in the main screen - tab logs.  it is possible to scroll left / right using the keyboard but that scrolling is slow.  It would be nice to be able to scroll left / right using the mouse.

an alternative could be to enable toggling wrapping text in the logs tab.

**Comment by Shardj** [comment]
I'd really appreciate text wrapping too, the logs are often useless because they cut off too early

**Comment by jesseduffield** [comment]
if you do
```
gui:
  wrapMainPanel: true
```
in your config (opened via pressing 'o' while the status panel is selected) then it should wrap text for you :)

**Comment by Shardj** [comment]
Pressing o while the status panel is selected causes notepad to try and launch but it very quickly crashes. Could I get the file path?

**Comment by alexandervanhecke** [comment]
@jesseduffield 👍 works like a charm, thanks

**Comment by alexandervanhecke** [comment]
@Shardj on MacOS the `config.yml`is in `~/Library/Application\ Support/jesseduffield/lazydocker`

**Comment by Shardj** [comment]
I'm on Ubuntu...
