### ISSUE TITLE
lazydocker with docker-desktop

### ISSUE THREAD

**Issue by thevan96** [jesseduffield/lazydocker#351]
I install docker-desktop for linux, but I love lazydocker because I like controlling docker in the terminal.
How to connect lazydocker with docker-desktop?

https://docs.docker.com/desktop/linux/install/#differences-between-docker-desktop-for-linux-and-docker-engine

**Comment by skanehira** [comment]
Is there has `/var/run/docker.sock` ?
If it exist, I think you can run lazydocker.

**Comment by thevan96** [comment]
> Is there has `/var/run/docker.sock` ? If it exist, I think you can run lazydocker.

Yes, it exist, but i can't connect lazydocker because docker-desktop run in VM

**Comment by NathanBaulch** [comment]
You need to enable WSL integration in your default WSL distro. You can find this under Settings | Resources | WSL Integration.

**Comment by jareis** [comment]
a better solution is the one mentioned on 
https://github.com/jesseduffield/lazydocker/issues/321#issuecomment-1173213912
