### ISSUE TITLE
Docker Desktop Extension?

### ISSUE THREAD

**Issue by FantasticFiasco** [jesseduffield/lazydocker#353]
**Describe the solution you'd like**
With the open beta of [Docker Desktop Extensions](https://docs.docker.com/desktop/extensions/), have you considered extending this fantastic UI to also run on Docker Desktop? It's a far stretch I imagine, and I wouldn't hold it against you if you said it was outside the scope of the project.

**Comment by amyb12345** [comment]
If you do choose to pursue creating a Docker Extension, the team at Docker is available to support you. You can find us in the [Docker Community Slack](http://dockr.ly/slack) in #extensions, post issues on our [SDK repo](https://github.com/docker/extensions-sdk), or reach us via email [extensions@docker.com](mailto:extensions@docker.com).
