### ISSUE TITLE
Make it clear that cheetsheets are auto-generated

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazydocker#369]
**Is your feature request related to a problem? Please describe.**
Sometimes somebody will raise a PR making manual changes to a cheatsheet file. These cheatsheet files are actually auto-generated and depend on files in pkg/i18n.

In [lazygit](https://github.com/jesseduffield/lazygit/blob/master/pkg/cheatsheet/generate.go#L71) we print a message at the top of the cheatsheet saying that it's auto-generated i.e.:
```go
		content = fmt.Sprintf("_This file is auto-generated. To update, make the changes in the "+
			"pkg/i18n directory and then run `%s` from the project root._\n\n%s", CommandToRun(), content)
```

We should do that here too in https://github.com/jesseduffield/lazydocker/blob/master/scripts/generate_cheatsheet.go

**Comment by gusandrioli** [comment]
I'll take this one.

**Comment by jesseduffield** [comment]
@gusandrioli go right ahead :) Let me know if you need any pointers
