### ISSUE TITLE
Check cheatsheet is up to date in CI

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazydocker#370]
**Is your feature request related to a problem? Please describe.**
In lazygit we have a cheatsheet [check script](https://github.com/jesseduffield/lazygit/tree/master/pkg/cheatsheet) which tells us whether the cheatsheet we currently have is in line with what would be generated by the cheatsheet generation script.

We want to port this over to lazydocker and also run it on CI (see the lazygit approach for [comparison](https://github.com/jesseduffield/lazygit/blob/master/.github/workflows/ci.yml#L161))

This will ensure that nobody accidentally makes a change while forgetting to update the cheatsheet

**Comment by gusandrioli** [comment]
I can take this one as well :)

**Comment by jesseduffield** [comment]
Go right ahead @gusandrioli  :)
