### ISSUE TITLE
0.19.0 tag, but no release

### ISSUE THREAD

**Issue by benalb** [jesseduffield/lazydocker#382]
There is a 0.19.0 tag, but there is no 0.19.0 realese. This happend previously [0.13](https://github.com/jesseduffield/lazydocker/issues/305)

This is more a heads up than a real issue, but still.

**Comment by jesseduffield** [comment]
Ah damnit my github token expired. Let me fix that up!

**Comment by jesseduffield** [comment]
Fixed @benalb . I'll close this off
