### ISSUE TITLE
Selected service automatically moves when there are multiple services with the same config

### ISSUE THREAD

**Issue by nakaakist** [jesseduffield/lazydocker#402]
**Describe the bug**

When there are multiple containers with the same config in `docker-compose.yml` like below, the selected service in the "Services" side panel automatically moves on every refresh, even though the user does not touch anything.

```
version: "3.9"
services:
  service-a:
    image: "nginx:latest"
  service-b:
    image: "nginx:latest"
  service-c:
    image: "nginx:latest"
```

**To Reproduce**
1. run `docker-compose up -d` with the `docker-compose.yml` above.
2. run `lazydocker`
3. wait for a few seconds, and see error

**Expected behaviour**

The selected service should be fixed when the user does not touch.

**Screenshots**

Following is the lazydocker monitor when the `docker-compose.yml` file shown above is used.
Even though I don't touch anything, the selected service moves (service-c -> service-b -> service-a).

https://user-images.githubusercontent.com/6212292/202889551-1f78209b-128e-42fc-9cf9-a1858f985130.mov

**Desktop (please complete the following information):**
 - OS: MacOS 13.0.1
 - Lazydocker Version:  0.20.0

**Additional context**

I encountered this problem during the development of a microservice system with similar docker-compose.yml pattern.

I guess the cause of the problem is:
- when the config of the container is the same, the [generated service ID becomes the same](https://github.com/jesseduffield/lazydocker/blob/master/pkg/commands/docker.go#L247).
- Then, [the logic to see if the selected service has moved](https://github.com/jesseduffield/lazydocker/blob/master/pkg/gui/containers_panel.go#L270) judges the service has moved, and re-selects the item.

**Comment by nakaakist** [comment]
Thanks. Yes, I'll try!

**Comment by jesseduffield** [comment]
Sweet, let me know if you run into any issues :)
