### ISSUE TITLE
Does not fully work on Kubuntu 18.04

### ISSUE THREAD

**Issue by Janealter** [jesseduffield/lazydocker#41]
Services and standalone containers are not displayed.

**Comment by dawidd6** [comment]
Docker version installed on your machine?
Compose version installed on your machine?
Lazydocker installation method and version as well on your machine?

Please provide some more information.

**Comment by piotrmacha** [comment]
I had similar problem running lazydocker on WSL with docker-compose
```
docker-compose version 1.17.1, build unknown
```
Updating docker-compose to newest version solved the problem
```
docker-compose version 1.24.0, build 0aa59064
```

You can find instructions for getting the newest version here on https://docs.docker.com/compose/install/#install-compose-on-linux-systems

**Comment by arpadszasz** [comment]
I can confirm the solution provided by @piotrmacha works for me on:
* Ubuntu 19.04 (disco)
* Docker version 18.09.5, build e8ff056 (from Ubuntu universe repo)
* **updated** docker-compose version 1.24.0, build 0aa59064

Thanks.

**Comment by markphip** [comment]
Had a colleague also run into this. Would be good to identify the minimum version required in the README.md.  This is what I have on MacOS where it works fine for me: `docker-compose version 1.23.2, build 1110ad01`

**Comment by cmpilato** [comment]
I'm the colleague @markphip mentioned, and can confirm that upgrading docker-compose to 1.24 solved the issue.
