### ISSUE TITLE
Using lazydocker on a remote docker daemon doesn't work

### ISSUE THREAD

**Issue by unixfox** [jesseduffield/lazydocker#42]
I'm trying to access to my remote docker daemon using lazydocker but that doesn't work and the program throw me that error:
````
2019/07/01 12:59:54 An error occurred! Please create an issue at https://github.com/jesseduffield/lazydocker/issues

*errors.errorString unable to parse docker host `192.168.192.1`
main.go:68 (0x8203f9)
/usr/lib/go/src/runtime/proc.go:200 (0x42f2ec)
	main: fn()
/usr/lib/go/src/runtime/asm_amd64.s:1337 (0x45a241)
	goexit: BYTE	$0x90	// NOP
````

Here is the environment variable I use in my `bashrc` to access to my remote Docker daemon:
````
export DOCKER_HOST=192.168.192.1
````

**Comment by piotrmacha** [comment]
Try adding `tcp://` before actual host like:
```
export DOCKER_HOST=tcp://192.168.192.1
```
It looks like Docker client for Go can not parse raw host without protocol

**Comment by unixfox** [comment]
Thank you this fixed my issue! I had to add the port too like this:
````
export DOCKER_HOST=tcp://192.168.192.1:2375
````
