### ISSUE TITLE
Is it possible to use Lazydocker with Colima on macOS

### ISSUE THREAD

**Issue by fosron** [jesseduffield/lazydocker#422]
Is it possible to use Lazydocker with Colima on macOS?

I'm getting this error ATM

```
lazydocker
2023/01/09 15:08:03 connection to docker client failed. You may need to restart the docker client
```

I found the socket URL using

```
colima status
...
INFO[0000] socket: unix:///Users/***/.colima/default/docker.sock
```

but i can't find a way to configure it.

**Comment by fosron** [comment]
Thanks 🙇

**Comment by blitzarx1** [comment]
I ve figured it out myself. 

But it seems strange to me that `docker ps` command worked as expected, but lazydocker can't find docker sock. It may be confusing for beginner and I was not able to find any info on that in documentation. Maybe we should add a note on it somewhere in troubleshooting? Or even make a PR which teaches lazydocker to pick currently selected context from `docker context ls` command for example?
