### ISSUE TITLE
Recent update of Docker seems to have broken lazydocker - MacOS X Ventura 13.4

### ISSUE THREAD

**Issue by otherwhitefrank** [jesseduffield/lazydocker#452]
**Describe the bug**
Running lazydocker where it worked previously brings up following message.
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Lazydocker --version

`
(base)  frank@Franks-Mac-Studio  ~/code/bunko   main ±  lazydocker --version
Version: 0.20.0
Date: 
BuildSource: homebrew
Commit: 
OS: darwin
Arch: arm64
`

Installed via docker .dmg, upgraded yesterday
`
(base)  frank@Franks-Mac-Studio  ~/code/bunko   main ±  docker --version
Docker version 24.0.2, build cb74dfc
`

docker-compose works fine
`
(base)  frank@Franks-Mac-Studio  ~/code/bunko   main ±  docker-compose --version
Docker Compose version v2.18.1
`

**To Reproduce**
1. Upgrade Docker on MacOS X to above referenced version
2. Run 'lazydocker'

**Expected behaviour**
Lazydocker runs correctly

**Screenshots**
![image](https://github.com/jesseduffield/lazydocker/assets/1350573/91e68409-9523-4b24-abfa-000085ddaf29)

**Desktop (please complete the following information):**
 - OS: MacOS Ventua 13.4
 - Lazydocker Version 0.20.0 (Installed via brew)

**Comment by mark2185** [comment]
But _is_ the `daemon` running?

Can you start docker containers, pull images, and so on, from the command line? If not, try launching `docker desktop` and try again.

**Comment by otherwhitefrank** [comment]
Yup docker, its CLI, the docker engine GUI, and docker-compose all work

`
(base)  frank@Franks-Mac-Studio  ~/code/bunko   main ±  docker-compose up
[+] Building 0.0s (0/0)                                                                                                
[+] Running 15/0
 ✔ Container bunko-frontend-1   Created                                                                           0.0s 
 ✔ Container bunko-postgres-1   Created                                                                           0.0s 
 ✔ Container bunko-rabbitmq-1   Created                                                                           0.0s 
 ✔ Container bunko-mongodb-1    Created                                                                           0.0s 
 ✔ Container bunko-vault-1      Created                                                                           0.0s 
 ✔ Container bunko-clamav-1     Created                                                                           0.0s 
 ✔ Container bunko-redis-1      Created                                                                           0.0s 
 ✔ Container bunko-yeti-1       Created                                                                           0.0s 
 ✔ Container bunko-api-1        Created                                                                           0.0s 
 ✔ Container bunko-celery-1     Created                                                                           0.0s 
 ✔ Container bunko-feeds-1      Created                                                                           0.0s 
 ✔ Container bunko-analytics-1  Created                                                                           0.0s 
 ✔ Container bunko-oneshot-1    Created                                                                           0.0s 
 ✔ Container bunko-exports-1    Created                                                                           0.0s 
 ✔ Container bunko-beat-1       Created                                                                           0.0s
`

**Comment by otherwhitefrank** [comment]
Think it may be this, looks like they moved the docker.sock to my local directory? 

```
836ae7eac192ac27 stream      0      0 836ae7eac5eeb9b7                0                0                0 /Users/frank/.docker/run/docker.sock
```

**Comment by otherwhitefrank** [comment]
Was able to get it to work again with following.

```
export DOCKER_HOST=unix:///Users/frank/.docker/run/docker.sock
```

Happy to close, would recommend a warning as I think at least the MacOS Docker is moving the docker.sock around (pretty sure mine wasn't local before, as lazydocker ran fine with no explicit DOCKER_HOST set). Thanks for help.
