### ISSUE TITLE
Add Rebuild keybinding

### ISSUE THREAD

**Issue by TJTorola** [jesseduffield/lazydocker#49]
**Is your feature request related to a problem? Please describe.**
I cannot find a keybinding for the rebuild command.

**Describe the solution you'd like**
I'd like for there to be some keybinding to rebuild a container/service.

**Describe alternatives you've considered**
The only alternative I can find is to rebuild my container outside of the app.

**Additional context**
it does appear that there is some source code to support that functionality, but it I don't see where it is hooked up in the keybindings section and it isn't listed in the menu section of the app as well.

**Comment by mcintyre94** [comment]
For services (not standalone containers), I have a `view restart options` item bound to `R` in the keyboard shortcuts, which includes restart, recreate and rebuild. Do you see that on services if you open it with a docker-compose context?

I think another workaround would be to use a custom command within lazydocker - see custom commands here: https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md

**Comment by TJTorola** [comment]
Ah I missed that, that will work fine, thanks!
