### ISSUE TITLE
rename a container

### ISSUE THREAD

**Issue by AlexRainHao** [jesseduffield/lazydocker#490]
Hi, I'm a newcomer around `lazygit`. I want to know, is there a way to rename a running container name?

I tried setting the custom command, but I have no idea how to read the new name in the panel.

**Comment by mark2185** [comment]
I believe `lazydocker` doesn't have prompts when it comes to custom commands, unlike `lazygit`.

@jesseduffield are there plans of porting and is it okay to port or are there plans that could interfere?

**Comment by AlexRainHao** [comment]
Thanks, it's good idea to support popup prompt panel in the future. Now I could rename each container through docker CLI, or directly use docker-compose to distinguish them
