### ISSUE TITLE
Cannot install on Debian 5.10.197-1 via curl .sh

### ISSUE THREAD

**Issue by Vargash** [jesseduffield/lazydocker#500]
**Describe the bug**
I'm trying to install the latest version using the curl method, but the operation seems to not work.
I get no error, but the binary seems like it's not downloaded.

**To Reproduce**
1. Connect to server with a normal user (not SU)
2. Execute  `curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash`
3. See error.

**Expected behaviour**
lazydocker is installed in `~/.local/bin`

**Screenshots**
![image](https://github.com/jesseduffield/lazydocker/assets/807174/d023c420-76ed-4319-b0d9-f943ad4797dc)

**Desktop (please complete the following information):**
 - OS: Debian 5.10.197-1
 - Lazydocker Version 0.23.1

**Comment by mark2185** [comment]
Is the `~/.local/bin` in your `PATH`?

If you comment out the three last lines in the `install_update_linux.sh`, i.e.
```
# install/update the local binary
curl -L -o lazydocker.tar.gz $GITHUB_URL
# tar xzvf lazydocker.tar.gz lazydocker
# install -Dm 755 lazydocker -t "$DIR"
# rm lazydocker lazydocker.tar.gz
```

Does it download the `lazydocker.tar.gz` in the current directory?

**Comment by Vargash** [comment]
Yep it does.
It looks like some permission problems with the default installation folder of the script, I reconfigured the user permission and all went well.
Probably some more verbose logging in the scripts could be useful in this cases, though.
