### ISSUE TITLE
Possibility to configure different servers to manage the Dockers and have then split on "tabs"

### ISSUE THREAD

**Issue by victorguidi** [jesseduffield/lazydocker#504]
Hey, hope everyone is doing great!

The company I work for has pretty much everything running on premise. One of my tasks is to manage dockers running on all of our servers, currently 5 with over 50 docker containers split on the servers.

I was considering implementing my own lazydocker until I came across this project, which is fantastic, congrats to everyone who contributed so far!! 
But back to the Issue, my intention was to implement my own lazydocker but with a feature that would allow me to have all my servers configured as tabs, so if I hit 1 I would be managing all dockers on my local machine, but if I hit 2 I would be able to manage all the dockers on server 11.11.55... You got the idea? 

Before I open this issue I started working on something, I was for each IP configured in a yml file, I opened a SSH instance in separate routines and send the docker commands to then. Then I saved the result and kept all the information for each docker in the different machines (in the tabs) so when I hit the number of the tab I would have already all the info. The problem of course is that I would have to keep the ssh session open in order to offer a more smooth feeling for the user.

Would you consider this feature something suitable and doable for the current state of Lazydocker? 

I am definitely willing to contribute to this feature, if thats something that you guys consider interesting in implementing in!

**Comment by mark2185** [comment]
Would the same be achieved if you pointed the `DOCKER_HOST` variable to a specific server and then launched `lazydocker`?

I.e. you'd have 5 terminals, and run `DOCKER_HOST=11.11.55.66 lazydocker` in one, `DOCKER_HOST=4.4.6.6 lazydocker` in the other etc. instead of having _tabs in `lazydocker`_, you'd have _`lazydocker` in tabs_?

**Comment by victorguidi** [comment]
Hey there, happy new year! 

Yeah that would work too

I mean I usually use tmux or Zellij so I could manage multiple sessions of lazydocker in different terminals if needed. 

For the server credentials, would that also be set in an environment variable? The idea of a yml file would be to set all servers and credentials in one place. But I wouldn't mind to set as individual variables too!! 

By the way, is this variable for docker host already available to be set?

**Comment by mark2185** [comment]
> For the server credentials, would that also be set in an environment variable? The idea of a yml file would be to set all servers and credentials in one place. But I wouldn't mind to set as individual variables too!!

Credentials of what sort exactly? I'd guess one could specify `user@ip`, but not passwords.

> By the way, is this variable for docker host already available to be set?

Yes! It's been there for a while.

**Comment by victorguidi** [comment]
The ssh package in golang has all the methods for authentication if I am not wrong, I guess for credentials here I meant authentication

But its okay, this solution already works here like a charm. 

Thank you so much!!
