### ISSUE TITLE
Locked out of terminal after editing config

### ISSUE THREAD

**Issue by pvande** [jesseduffield/lazydocker#51]
**Describe the bug**
After editing my config from "inside" lazydocker, I was faced with a prompt that would not actually *accept* any input.

**To Reproduce**
1. Go to 'Status'
2. Click on 'About'
3. Press 'e' to edit the config
4. Exit vim with `:q`
5. Press 'Enter' to dismiss the prompt

**Expected behaviour**
I should be taken back to lazydocker's UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/2350/60451542-2576cb80-9be1-11e9-888c-7fd65ea66221.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Lazydocker Version 0.2.4 (from Homebrew)

**Additional context**
This issue does not consistently reproduce for me.  It triggered for me in a session where I'd been exploring for a while, but I haven't seen it again in a new session.

**Comment by jesseduffield** [comment]
I've seen this myself a couple times too. I believe it's an issue with how we're using termbox-go. termbox-go wasn't really made to be initialized and closed multiple times in a single session, so it has some package-level variables being used for state. I think that's the core of the issue: it might take a bit of work on the termbox-go fork to make it deal better with e.g. exiting PollEvent() when we want it to, and then being able to listen for more events when we call PollEvent() again. I think it's something along those lines

**Comment by ghostsquad** [comment]
Package level variable anti pattern strikes again!

**Comment by jesseduffield** [comment]
I haven't had this problem for a while so I'll close this off. If other people still get the issue let me know and we can reopen
