### ISSUE TITLE
Move the panel with number like lazygit

### ISSUE THREAD

**Issue by jiyeol-lee** [jesseduffield/lazydocker#522]
**Is your feature request related to a problem? Please describe.**
I get used to the feature switching panel in lazygit using number, but it's very frustrating to focus the different panel using mouse.

**Describe the solution you'd like**
In lazygit, you can change the focus pressing the number but lazydocker does not have that feature. Would it be possible to add that feature? So, if you press `1`, `Project` panel focus, `2`, `Services` panel focus, etc.

**Describe alternatives you've considered**
--

**Additional context**

**Comment by peauc** [comment]
Trying to add it to lazydocker :eyes:

**Comment by joehays** [comment]
I second this request. It's very irritating that I have to use my mouse at all. We should be able to navigate to everything without ever touching the mouse.

**Comment by mark2185** [comment]
> I second this request. It's very irritating that I have to use my mouse at all.

Can't you `<Tab>` beteeen them?

**Comment by Tazoeur** [comment]
I also had to arrive here to see that `<Tab>` allows the user to move between the Project-Containers-Images-Volumes-Networks panels.

I would still be fond of the number-like shortcuts, but adding this information to the keymaps documentation would be helpful for some people.

**Comment by jiyeol-lee** [comment]
> Can't you <Tab> beteeen them?

Yes, it works but I'm getting used to switch between tabs using number-like shortcuts. One of the lazyXX app works but the other is not working. If we didn't have the number-like shortcut from the lazygit, then I might also just using it and not create this issue.

**Comment by peauc** [comment]
The attached PR should fix this issue and should land on the next version
