### ISSUE TITLE
Repository with Port

### ISSUE THREAD

**Issue by cumminsd** [jesseduffield/lazydocker#56]
**Describe the bug**
If you have a repository that uses a port number, the display in LazyDocker shows incorrectly:

**To Reproduce**
Set up a local repository and use port 5000

Running:
$ docker images

Gives:
```
REPOSITORY                             TAG                      IMAGE ID     CREATED        SIZE
my.repository.net:5000/tool          latest                    abcdefghijk   6 days ago        1.8GB
```
But shows in LazyDocker as:
```
my.repository.net                          5000/tool                  1.8GB
```

**Expected behaviour**
LazyDocker should show:
```
my.repository.net:5000/tool          latest                         1.8GB
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Lazydocker Version: "commit=, build date=, build source=unknown, version=unversioned, os=linux, arch=amd64"

**Comment by jesseduffield** [comment]
interesting. I think this might be semi-easy to fix so I'm gonna chuck a 'good first issue' label on this. Happy to give guidance if anybody wants to have a crack at fixing it :)

**Comment by vedelaar** [comment]
I had this problem too, created a pull request with my changes. #59

**Comment by jesseduffield** [comment]
closing :) let me know if we need to do anything else

**Comment by cumminsd** [comment]
Works perfectly! Thank you!
