### ISSUE TITLE
Weird look on iTerm vs Terminal on macOS

### ISSUE THREAD

**Issue by AlexLombry** [jesseduffield/lazydocker#61]
**Describe the bug**
Weird look on iTerm2 vs Terminal

I'm still tweaking my configuration but i always have that kind of behaviour.
I'm running oh my zsh on both iterm and terminal.

**Screenshots**
__macOS Built in terminal__
![Terminal](https://imgshare.io/images/2019/07/02/terminal.png)

__iTerm2__
![iTerm2](https://imgshare.io/images/2019/07/02/iterm.png)

**Desktop :**
 - OS: macOS High Sierra 
 - brew info lazydocker
 - jesseduffield/lazydocker/lazydocker: stable 0.2.4

**Comment by subfission** [comment]
Had a problem like this for a different project, turned out to be font related...  Might be your issue.

**Comment by jesseduffield** [comment]
As @subfission said, I think this just comes down to the font being used. If you change it to the same font as what you're using in iterm I believe it will fix the issue

**Comment by AlexLombry** [comment]
It's the same font, SF Mono regular 14pt.

**Comment by jesseduffield** [comment]
I'm stumped. Do you have any examples of other TUI programs that run fine with that font in iterm2?

**Comment by AlexLombry** [comment]
Irssi work fine everywhere.

I tested on Hyper, Terminal and Hyper.

The problem appears for LazyDocker and LazyGit only on iTerm.
For Hyper and Terminal everything's fine.

If you have other TUI for testing tell me :)

**Comment by jesseduffield** [comment]
Lazygit and Lazydocker both the gocui library. It might be worth trying out another project made with the gocui library and seeing if they have the same issue:

https://github.com/jroimartin/gocui#projects-using-gocui

If so, you may need to raise an issue there

**Comment by AlexLombry** [comment]
Yes i'll go there to make the same issue, i've tried other gocui made tools and it's the same problem so it's gocui.

I'll close the issue, thank you :)
