### ISSUE TITLE
Automatically push to dockerhub as part of CI pipeline

### ISSUE THREAD

**Issue by jesseduffield** [jesseduffield/lazydocker#66]
**Is your feature request related to a problem? Please describe.**
It would be cool if we built the lazydocker image and pushed to docker hub as part of the CI pipeline when we do a release

**Comment by glvr182** [comment]
You can setup Autobuild on dockerhub aswell. See [this](https://docs.docker.com/docker-hub/builds/)

**Comment by dawidd6** [comment]
Yes, can confirm that @glvr182 . It's really straightforward. Just Github login is required.
hub.docker.com

**Comment by qdm12** [comment]
Hey @jesseduffield  what's your Docker Hub username? For readme badges purposes

You can setup autobuilds [here](https://cloud.docker.com/repository/create) and then you can get a webhook link for nice badges of the Docker image size and version at [https://microbadger.com/images/jesseduffield/lazydocker](https://microbadger.com/images/jesseduffield/lazydocker)

**Comment by qdm12** [comment]
You may want to use Circle CI to build the Docker image and push it to Docker Hub as well. This is great as everything takes place in the same place and it will fail if there is an integration bug.

However, I think that an automated build with Docker Hub is more trustworthy as it's hard for the user to find the origin of the Docker push (which should be Circle CI) to Docker Hub (a.k.a. malicious Docker images not corresponding to Github's repository source code)

**Comment by jesseduffield** [comment]
@qdm12 not sure if you saw my comment in your PR but we can use the dockerhub username of 'lazyteam' and the repo of 'lazydocker'. 

What are your thoughts on us using goreleaser to handle building and pushing the image? We currently use it for building the binaries, homebrew, and snapcraft. And it has support for docker as well: https://goreleaser.com/docker/

**Comment by qdm12** [comment]
As you wish, the only thing is that any other party than Docker Hub would have to `docker push` from outside so it's not great security wise for careful users (although probably not many!).

For example, Linuxserver push all their images from their CI but I'm not sure the user can actually verify this. So it could be a malicious/corrupted image they pushed manually from their desktop for example.

On my side, I always have automated Docker Hub builds linked to Github **for x86_64**. I however push ARM images from an ARM device I have as there is no CI/Docker Hub solution to build efficiently for ARM devices...

**Comment by jesseduffield** [comment]
from your experience is it simple enough to hook everything up with the docker hub approach @qdm12 ?

**Comment by qdm12** [comment]
Yes, it's 15 key strokes and 5 mouse clicks, [here](https://cloud.docker.com/repository/create) 😸 
Plus you can add a bit of CI-like features to Docker Hub build using files in the *hooks* directory if you want to.

But you should have both a CI and Docker Hub, which builds all Docker images *only*.

**Comment by jesseduffield** [comment]
How does this look to you?
![image](https://user-images.githubusercontent.com/8456633/60724636-59a01280-9f7a-11e9-8a7f-292ff190f036.png)
Also I'm guessing we wouldn't want to actually set this up until your PR is merged, correct?

**Comment by qdm12** [comment]
- You could add a `latest` docker tag build from the master branch of the latest Github tag. By default Docker will pull the `latest` tag if not tag is specified, i.e. `docker run -it lazyteam/lazydocker` so it's a good idea to have a `latest` tag 👍 
- I was not aware of that new [AUTOTEST feature](https://docs.docker.com/docker-hub/builds/automated-testing/) that could be of interest!

**Comment by jesseduffield** [comment]
done :)
![image](https://user-images.githubusercontent.com/8456633/60725769-42aeef80-9f7d-11e9-948a-2e8adc4327fa.png)

**Comment by qdm12** [comment]
Cool! It will pickup the new Dockerfile and build hooks when we merge the docker PR.

**Comment by jesseduffield** [comment]
sounds good
