### ISSUE TITLE
Text is not selectable

### ISSUE THREAD

**Issue by jrmgx** [jesseduffield/lazydocker#68]
**Describe the bug**
When running the command on macos last version, basic Terminal app, basic shell
I cannot select any text from the display.
Clicking works but it seems it prevents selecting (I guess)

**To Reproduce**
1. Start lazydocker
2. Try to select something 

**Expected behaviour**
I expect that (as any other term command) the text could be selected

**Desktop (please complete the following information):**
 - OS: macos 10.14.5
 - Lazydocker Version Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=darwin, arch=amd64

**Back story**
I just wanted to select some docker id so I could stop it, maybe a stop action could be a plus?

**Comment by MisterGlass** [comment]
Would like this as well. I was attempting to copy an error from my docker logs but could not because the text was not selectable

**Comment by jesseduffield** [comment]
on mac, you can hold 'option' while dragging the mouse to select text. This has however been brought up before, perhaps we should add a FAQ to the about page in the app? or the readme?

**Comment by jrmgx** [comment]
Thank you for this information.
I think it could be added to the FAQ for sure. Good support anyway.
Have a good day

**Comment by MisterGlass** [comment]
Is there any way to select text on windows?

**Comment by damianchoc** [comment]
will it be added to lazydocker?

**Comment by mjarkk** [comment]
```
gui:
  mouseEvents: false
```
You can try adding that to the lazydocker config (`Go to Project > press e`)  
*this will disable all mouse support so text select is supposed to work again*

**Comment by cardin** [comment]
For Windows (Win Terminal WSL), it seems to be SHIFT key + Mouse Drag to select.

**Comment by hipertracker** [comment]
Adding it on macos does not work

```
gui:
  mouseEvents: false
```
