### ISSUE TITLE
Error during connect: ... /var/run/docker.sock: socket: too many open files

### ISSUE THREAD

**Issue by ravenchilde** [jesseduffield/lazydocker#72]
**Describe the bug**
MacOS Mojave, installed with brew, ran "Lazydocker" in terminal, and got Error: error during connect: Get http://var/run/docker.sock/v1.25/containers/...<hash>.../stats?stream=1: dial unix /var/run/docker.sock: socket: too many open files

**To Reproduce**
1. Have a couple swarm mode stacks running
2. Open terminal, run: lazydocker
3. See error

**Expected behaviour**
Lazydocker works

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Lazydocker Version: Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=darwin, arch=amd64

**Additional context**
I have 337 containers when I ls.

**Comment by jesseduffield** [comment]
do you still get the same error if you have no containers running?

**Comment by ravenchilde** [comment]
I do not. 

C.

**Comment by jesseduffield** [comment]
I'm gonna close this due to staleness. If you're still experiencing the issue I'll reopen
