### ISSUE TITLE
Keeping stats view open for a while produces `index out of range` error

### ISSUE THREAD

**Issue by sardaukar** [jesseduffield/lazydocker#76]
**Describe the bug**
Keeping the stats window open for a given container for long periods of time eventually crashes with `panic: runtime error: index out of range`.

**To Reproduce**
1. selecting a running container
2. select stats view
3. wait for a while (I've seen it happen in a couple of hours)
4. see error

**Expected behaviour**
Stats view to not crash ever

**Screenshots**
![Screenshot from 2019-07-03 05-27-20](https://user-images.githubusercontent.com/153407/60563327-43643d80-9d53-11e9-8c9d-1db34690e229.png)

**Desktop (please complete the following information):**
 - OS: Debian Linux 9.9
 - Lazydocker `commit=50a6eb64ece25bc85c95c7223f6100bdbae6c69c, build date=2019-06-30T11:09:18Z, build source=binaryRelease, version=0.2.4, os=linux, arch=amd64`

**Comment by sardaukar** [comment]
Still happens in `commit=572ff63e858150d9cbec6f1ed67ff6d04258c9c0, build date=2019-07-03T14:21:59Z, build source=binaryRelease, version=0.4, os=linux, arch=amd64`

**Comment by mjarkk** [comment]
@sardaukar @stdedos This will probably be fixed in the next release.

**Comment by ccalvarez** [comment]
This is happening in Version: 0.24.1 on Windows:

![Image](https://github.com/user-attachments/assets/d6148aef-3680-44bb-b3a4-63aca9786419)

As soon as I click on Stats, it crashes with error:

panic: runtime error: index out of range [-9223372036854775808]

![Image](https://github.com/user-attachments/assets/ba3cc6ac-3809-4cc9-8037-1492d5022948)
