### ISSUE TITLE
Add some docker-compose config-wide shortcuts

### ISSUE THREAD

**Issue by mcintyre94** [jesseduffield/lazydocker#78]
**Is your feature request related to a problem? Please describe.**
When starting lazydocker in a docker-compose context with nothing currently running, there's no way to run docker-compose commands like build, pull, up on them all together

**Describe the solution you'd like**
I'm not entirely sure, but maybe adding config-wide options to the keyboard shortcuts under `Status`, given that already has a tab with docker-compose config? b: build all, p: pull all, u: up all would all be useful IMO and don't conflict with current shortcuts in that section.

I'm not sure though because the current shortcuts there are really about lazydocker itself.

**Describe alternatives you've considered**
I could always use docker-compose commands outside of lazydocker! Just being lazy :)

**Additional context**
Sometimes I'll want to run tests locally on a branch that I haven't built locally, and that our CI has already built. In those cases I want to do `docker-compose pull` or `docker-compose build` to pull/build all of the images for that branch together. It'd just be nice if I could pull all of that into lazydocker too :)

**Comment by jesseduffield** [comment]
I 100% agree with this. I see no harm in having lazydocker-specific keybindings sitting alongside docker-compose-specific keybindings

**Comment by markphip** [comment]
I was also thinking about this. Combined with the -f option in my case.  Was thinking could possibly even replace a lot of the shell script we use which basically just runs things like up -d, down, logs etc. with the right set of files provided via the -f.  I could see changing our workflow to just launching lazydocker from our script that manages the set of files using -f and then you could do up,down etc. from lazydocker while the rest of the UI already replaces the other things we do.

**Comment by mcintyre94** [comment]
Lazydocker has super nice architecture around these commands - we get interop of everything else with -f for free by just referencing the `{{ .DockerCompose }}` at the start of all the commands. :)

**Comment by jesseduffield** [comment]
@mcintyre94 did you want to tackle this issue yourself?

**Comment by mcintyre94** [comment]
I'm happy to give it a shot when I get some time, but equally happy for someone else to beat me to it - if you or someone else want to give it a shot then got for it :)

**Comment by jesseduffield** [comment]
I've got a WIP PR up now: https://github.com/jesseduffield/lazydocker/pull/107

**Comment by mcintyre94** [comment]
Closing with #107 - thanks @jesseduffield! :)
