### ISSUE TITLE
aarch64 -> amd64 binary

### ISSUE THREAD

**Issue by nuxdie** [jesseduffield/lazydocker#83]
**Describe the bug**
using `curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash` command fails is the system arch is `aarch64`

**To Reproduce**
1. Go to a machine with `aarch64` architecture
2. Execute `curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash`
3. See error: `ERROR 404: Not Found.`

**Expected behaviour**
Installation completed with `lazydocker_0.3_Linux_arm64.tar.gz` instead of non-existent `lazydocker_0.3_Linux_aarch64.tar.gz` installed

**Error log**
```
--2019-07-03 13:24:54--  https://github.com/jesseduffield/lazydocker/releases/download/v0.3/lazydocker_0.3_Linux_aarch64.tar.gz
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-07-03 13:24:54 ERROR 404: Not Found.


gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'lazydocker': No such file or directory
```

**Additional context**
It would be nice to map `lazydocker_0.3_Linux_arm64.tar.gz` binary to `lazydocker_0.3_Linux_aarch64.tar.gz`

**Comment by dawidd6** [comment]
@immanuelfodor

**Comment by immanuelfodor** [comment]
Hi Guys, PR #85 should solve the issue. I can't reproduce it as I don't have an aarch64 machine, but the change should work fine.
