### ISSUE TITLE
Difficult to use with light background

### ISSUE THREAD

**Issue by 00001** [jesseduffield/lazydocker#9]
Much of the text in the UI is close to unreadable with a light background.

Tested with:
xterm -bg lemonchiffon
gnome-terminal (with default settings)

Otherwise it's great on black background.

Cheers!

**Comment by jesseduffield** [comment]
Agreed, it does not look too good on a white background. I think the main issue is that I'm forcing the text to be white in some places when what I really mean is that I want the text to be the default foreground color. I've gone and fixed up a heap of those places, and testing on my end the UI is fairly readable now.

Here's the release with the changes: https://github.com/jesseduffield/lazydocker/releases/tag/v0.2.3

**Comment by gabel** [comment]
Does 0.3 include the changes?  

Basis font looks ok but tabs and border colors are missing

iterm light theme

![image](https://user-images.githubusercontent.com/242039/60580775-f77ebc00-9d85-11e9-880f-a60b3a6f86ad.png)

dark theme

![image](https://user-images.githubusercontent.com/242039/60580906-2c8b0e80-9d86-11e9-8649-c423f81b9316.png)

**Comment by mjarkk** [comment]
@gabel For the border issue,  
You can change the border color in the config: `lazydocker > Status > "o"`  

You could do something like this:  
```yml
gui:
  theme:
    inactiveBorderColor:
    - black
```
https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md

**Comment by gabel** [comment]
@mjarkk Thank you that helped! It solves border color and tab font color issues. Might be useful to have something like the `inverst` mode that [ctop](https://github.com/bcicen/ctop#options) has.


![image](https://user-images.githubusercontent.com/242039/60589296-75988e00-9d99-11e9-9fc3-a501e5408d12.png)



 Status > `o` gave me 

![image](https://user-images.githubusercontent.com/242039/60589143-0c187f80-9d99-11e9-8bb4-3967b56005e2.png)

But just editing with vim worked.

`vim /Users/foobar/Library/Application\ Support/jesseduffield/lazydocker/config.yml`

**Comment by jesseduffield** [comment]
I've updated the default config to use the default color on border frames too, so others won't need to update their config for this :)

**Comment by 00001** [comment]
Thanks, looks great now!

**Comment by jesseduffield** [comment]
Awesome :) closing
