### ISSUE TITLE
Snap package not found

### ISSUE THREAD

**Issue by ggarnier** [jesseduffield/lazydocker#95]
**Describe the bug**
Can't install lazydocker via snap

**To Reproduce**
```
$ snap install lazydocker
error: snap "lazydocker" not found
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by dawidd6** [comment]
Yes, yes. We are working on it. Need to temporarily remove it from README.

**Comment by jesseduffield** [comment]
We are awaiting a manual review for lazydocker given that we require the 'classic' confinement.

You can see progress here https://forum.snapcraft.io/t/request-for-classic-confinement-for-lazydocker/12155/1

I'll close this for now
